/**
 * `sharing` namespace — user-facing copy for the sharing feature (ADR 0013).
 * Feature-self-contained: every sharing string lives here. Generic actions/states
 * are reused from the `common` namespace via `t('common:…')` and are NOT duplicated.
 */
export const messages = {
  orgsEmptyClause: 'Share links belong to an organization',
  orgsFailedClause: 'The share links were never requested',
  resourcesFailed: 'Could not load resources — try again',
  // Page chrome
  eyebrow: 'Platform',
  title: 'Sharing',
  lede: 'Mint unguessable public links to a page or knowledge collection.',

  // Gating / empty states
  notEnabledTitle: 'Sharing is not enabled',
  notEnabledBody: 'Ask an administrator to enable the Sharing feature for this tenant.',

  // aria-labels
  orgPickerLabel: 'Organization',

  // Resource-type display labels
  typeCmsPage: 'CMS page',
  typeKbCollection: 'KB collection',

  // Mint form
  mintTitle: 'Create a share link',
  fieldResourceType: 'Resource type',
  fieldResource: 'Resource',
  resourcePlaceholder: '— select —',
  fieldLabel: 'Label (optional)',
  labelPlaceholder: 'e.g. Draft for review',
  fieldExpiry: 'Expires in days (optional)',
  expiryPlaceholder: 'never',
  createLink: 'Create link',

  // Active links
  activeTitle: 'Active links',
  filterPlaceholder: 'Filter links…',
  filterAria: 'Filter share links by label',
  noMatchBody: 'No link matches your search.',
  clearSearch: 'Clear search',
  noActiveLinks: 'No active share links.',
  expiresAt: 'expires {{date}}',
  copyLinkLabel: 'Copy public link',
  linkCreatedCopied: 'Link created — URL copied to your clipboard.',
  linkMintedOnce: 'Copy this link now — it is shown only once:',
  dismissMinted: 'Dismiss',
  fingerprintTitle: 'The URL is never stored',
  fingerprintLabel: 'Fingerprint {{fingerprint}}…',
  revokeLinkLabel: 'Revoke',

  // Toasts
  linkCopied: 'Link copied',
  linkCreated: 'Share link created',
  loadFailed: 'Failed to load links.',
  createFailed: 'Create failed.',
  revokeFailed: 'Revoke failed.',
  typeCreativeBrief: 'Creative brief',
  typeBookingManage: 'Booking (app-minted)',
  typeSignRequest: 'Signature invite (app-minted)',
  expiryInvalid: 'Enter a whole number of days (1–3650), or leave empty for no expiry.',
  linksFailedTitle: 'Couldn’t load this workspace’s links',
  linksFailedBody: 'Something went wrong on our end — your links most likely still exist. Try again.',
  retryLabel: 'Retry',
  revokeDone: 'Link revoked — it stops working immediately.',
  seenCount_one: 'Seen {{count}} time',
  seenCount_other: 'Seen {{count}} times',
  lastSeenOn: 'Last seen {{date}}',
  viewCapLabel: 'view cap {{n}}',
  createdOn: 'created {{date}}',
  systemLinksToggle: 'App-minted links ({{n}}) — booking, signature and order links',
  noMineLinks: 'No links minted by people yet — the links below were created by the app.',
  showMoreLinks: 'Show {{n}} more',
  quoteSubtotal: 'Subtotal',
  revokeShareConfirm: 'Revoke this share link? Anyone with the URL loses access.',
  typeDocument: 'Document',
  typeConversation: 'Conversation',
  typePrompt: 'Prompt',
  typeCommerceQuote: 'Quote',
  typeCommerceOrder: 'Order',
  typeAppBuilderCanvas: 'App design',

  typeSlidesCanvas: "Slide deck",

  // Public read-only viewer (ADR 0122 Phase 6)
  publicReadOnly: 'Read-only shared view',
  publicSnapshotAt: 'Snapshot from {{when}}',
  publicExpiresAt: 'link expires {{when}}',
  publicLoading: 'Loading the shared view',
  publicUntitled: 'Shared conversation',
  publicEmpty: 'Nothing to show here.',
  publicGoneTitle: 'This link is no longer available',
  publicGoneBody: 'The share link may have been revoked by its owner, it may have reached its view limit, or the content it points to is no longer being shared.',
  publicLiveView: 'Live view — the owner can still change this content',
  publicExpiredTitle: 'This link has expired',
  publicExpiredBody: 'The owner set an expiry on this link and it has passed. Ask them for a fresh link.',
  publicLoadFailedTitle: 'Couldn’t load this shared view',
  publicLoadFailedBody: 'Something went wrong on our end — the link most likely still works. Try again.',
  publicRetry: 'Retry',
  publicDraftedByAgent: 'Drafted by an AI agent',
  publicGeneratedByWorkflow: 'Generated by an automated workflow',
  publicPoweredBy: 'Shared from',
  quoteChip: 'Quote',
  quoteTitle: 'Your quote',
  quoteValidUntil: 'Valid until',
  quoteTotal: 'Total',
  quoteAccept: 'Accept this quote',
  quoteAccepting: 'Accepting…',
  quoteAccepted: 'Quote accepted — order {{order}} was recorded. The seller will follow up about payment.',
  quoteAcceptFailed: 'Accepting the quote failed — it may have expired or changed.',
  quoteNotOpen: 'This quote is not open for acceptance right now.',
  frameViewsToggle: "Views by slide",
  frameViewsLoading: "Loading\u2026",
  frameViewsEmpty: "No slide views yet.",
  frameViewsUnavailable: 'View counts couldn\u2019t be loaded.',
  frameViewsSlide: "Slide {{n}}",

  // SHARE-UX-1/2/3 — link STATUS (a row carried none), the honest
  // expired/orphaned copy, and the copy-outcome-dependent mint claims.
  statusLive: 'Live',
  statusExpiring: 'Expires soon',
  statusExpired: 'Expired',
  statusRevoked: 'Revoked',
  statusOrphaned: 'Content deleted',
  // SHARE-1 HONESTY — the gate made document/commerce/creative-brief links
  // darkenable, and the row used to render “Live” for them anyway.
  statusCapReached: 'View limit reached',
  capReachedBody: 'This link hit its limit of {{n}} view(s), so it now shows “not available” to anyone who opens it. View limits cannot be raised — mint a new link if you still need to share this.',
  statusFeatureOff: 'Feature turned off',
  featureOffBody: 'An admin turned off the {{feature}} feature for this workspace, so this link now shows “not available” to anyone who opens it. Turn the feature back on to restore it, or revoke the link.',
  expiredAt: 'expired {{date}}',
  resourceMissingBody: 'The content this link pointed to no longer exists — anyone opening it is told the content was deleted. Revoke it to tidy up.',
  deadLinksToggle: 'Expired and revoked links ({{n}})',
  linkCreatedNotCopied: 'Link created — but it could NOT be copied. Copy it from the box above now; it is never shown again.',
  linkMintedCopyFailed: 'Copy this link manually — the clipboard was blocked and it is shown only once:',
  publicResourceGoneTitle: 'This shared content was deleted',
  publicResourceGoneBody: 'The link still works, but the page, document or design it pointed to no longer exists. Ask whoever shared it for an up-to-date link.',
} as const;
