/**
 * Break-glass operator login (ADR 0389 Phase 3) — the last-resort door when
 * every normal auth path is down (IdP outage, SSO misconfiguration). OFF by
 * default and invisible: unless OPENWOP_BREAKGLASS_ENABLED=true the route
 * 404s like it doesn't exist.
 *
 *   POST /v1/host/openwop-app/auth/break-glass   { token }
 *
 * Design (all fail-closed):
 *  - The credential is a LONG random token whose scrypt hash lives in
 *    OPENWOP_BREAKGLASS_TOKEN_HASH (`scrypt$<saltB64>$<hashB64>`, generated by
 *    `npm run breakglass:hash` — see bottom). The plaintext exists only in the
 *    operator's vault. node:crypto scrypt + timingSafeEqual — no new dep.
 *  - Success mints a SHORT-TTL (10 min), NON-refreshing user-tier cookie bound
 *    to OPENWOP_BREAKGLASS_TENANT, which MUST be listed in
 *    OPENWOP_SUPERADMIN_TENANTS — a misconfigured tenant refuses rather than
 *    minting a useless (or worse, wrongly-scoped) session.
 *  - SINGLE-USE per token: a durable CAS-claimed marker (keyed by the token
 *    hash) burns the token on first successful use across instances; re-arming
 *    means rotating OPENWOP_BREAKGLASS_TOKEN_HASH.
 *  - LOUD: every attempt (success or denial) chains a tamper-evident
 *    `security.breakglass-*` audit row (ADR 0389 P2 posture) and a success
 *    notifies every durable member of the break-glass tenant (ADR 0010).
 *  - Brute-force: 5 attempts / 15 min per IP, in-route sliding window.
 *  - The path is in PUBLIC_PATH_PREFIXES (the SAML-ACS precedent: the token IS
 *    the credential) — a hardened posture (OPENWOP_AUTH_DISABLE_COOKIES /
 *    ENFORCE_BEARER) must not 401 the operator before the route runs; that
 *    lockout is exactly the scenario break-glass exists for.
 */

import type { Express, Request } from 'express';
import { randomBytes, scrypt as scryptCb, scryptSync, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';

const scryptAsync = promisify(scryptCb) as (password: string, salt: Buffer, keylen: number, opts: { N: number; r: number; p: number }) => Promise<Buffer>;
import { OpenwopError } from '../types.js';
import { DurableCollection } from '../host/hostExtPersistence.js';
import { appendAudit } from '../host/auditChainService.js';
import { getNotificationEmitter } from '../notifications/emitter.js';
import { listMembers } from '../host/accessControlService.js';
import {
  signSession,
  setSessionCookie,
  base64urlEncode,
  type SessionPayload,
} from '../middleware/cookieSession.js';
import { createLogger } from '../observability/logger.js';

const log = createLogger('routes.breakGlass');

const SESSION_TTL_S = 600; // 10 minutes, non-refreshing
const MAX_ATTEMPTS = 5;
const WINDOW_MS = 15 * 60_000;

/** Durable single-use burn marker, CAS-claimed (insert-if-absent) so exactly
 *  one login wins a given token across instances. */
interface BurnMarker { hashKey: string; usedAt: string; ip: string }
const burns = new DurableCollection<BurnMarker>('security:breakglass-burn', (b) => b.hashKey);

// In-route brute-force window (mirrors middleware/rateLimit.ts idioms — that
// module's factories are path-specific, so a tiny local window beats exporting
// a general one for a single cold route).
const attemptTimes = new Map<string, number[]>();

function clientIp(req: Request): string {
  // GRADE-PASS 2026-07-17 (SEC-C3): the FIRST x-forwarded-for hop is client-
  // supplied and freely rotatable — a spoofing caller could sidestep the
  // window AND grow the map unboundedly. Behind Cloud Run/one trusted proxy
  // the RIGHTMOST entry is the proxy-appended peer address; fall back to the
  // socket.
  const fwd = req.header('x-forwarded-for');
  const hops = fwd ? fwd.split(',').map((h) => h.trim()).filter(Boolean) : [];
  return (hops.length > 0 ? hops[hops.length - 1] : req.socket.remoteAddress) ?? 'unknown';
}

function enabled(): boolean {
  return process.env.OPENWOP_BREAKGLASS_ENABLED === 'true';
}

/** Parse `scrypt$<saltB64>$<hashB64>`; null when unset/malformed. */
function parseTokenHash(): { salt: Buffer; hash: Buffer } | null {
  const raw = process.env.OPENWOP_BREAKGLASS_TOKEN_HASH ?? '';
  const parts = raw.split('$');
  if (parts.length !== 3 || parts[0] !== 'scrypt') return null;
  try {
    const salt = Buffer.from(parts[1]!, 'base64');
    const hash = Buffer.from(parts[2]!, 'base64');
    if (salt.length < 8 || hash.length !== 32) return null;
    return { salt, hash };
  } catch {
    return null;
  }
}

/** Constant-time verify. ASYNC scrypt (grade-pass SEC-C3): the sync variant
 *  blocked the event loop ~50-100ms per attempt on a PUBLIC path — a
 *  request-spray DoS vector on an armed deploy. */
async function verifyToken(token: string, parsed: { salt: Buffer; hash: Buffer }): Promise<boolean> {
  const derived = await scryptAsync(token, parsed.salt, 32, { N: 16384, r: 8, p: 1 });
  return timingSafeEqual(derived, parsed.hash);
}

/** CLI helper (scripts can import this): hash a fresh token for the env var. */
export function hashBreakGlassToken(token: string): string {
  const salt = randomBytes(16);
  const hash = scryptSync(token, salt, 32, { N: 16384, r: 8, p: 1 });
  return `scrypt$${salt.toString('base64')}$${hash.toString('base64')}`;
}

async function auditAndNotify(kind: string, tenantId: string, payload: Record<string, unknown>, notifyTitle?: string): Promise<void> {
  await appendAudit(tenantId, kind, payload).catch((err) =>
    log.error('breakglass_audit_failed', { kind, error: err instanceof Error ? err.message : String(err) }),
  );
  if (!notifyTitle) return;
  await notifyMembers(tenantId, payload, notifyTitle);
}

/** ADR 0010: a successful break-glass MUST be visible to the tenant's humans.
 *  Best-effort — delivery failure never blocks (the audit row is the record). */
async function notifyMembers(tenantId: string, payload: Record<string, unknown>, notifyTitle: string): Promise<void> {
  try {
    const members = await listMembers(tenantId, tenantId);
    const users = members.map((m) => m.subject).filter((s): s is string => typeof s === 'string' && s.startsWith('user:'));
    for (const recipientUserId of users) {
      await getNotificationEmitter().emit({
        tenantId,
        recipientUserId,
        type: 'security.breakglass',
        priority: 'high',
        title: notifyTitle,
        message: `Break-glass operator login at ${payload.at as string} from ${payload.ip as string}. If this was not you, rotate OPENWOP_BREAKGLASS_TOKEN_HASH immediately.`,
      }).catch(() => undefined);
    }
  } catch (err) {
    log.warn('breakglass_notify_failed', { error: err instanceof Error ? err.message : String(err) });
  }
}

export function registerBreakGlassRoutes(app: Express): void {
  // GRADE-PASS DATAG-4/DATAG-6 boot checks: (a) the single-use burn marker is
  // only exactly-once across instances on SHARED storage — warn when armed on
  // memory:// (each instance would admit one use); (b) the reserved
  // `host-admin` audit pseudo-tenant must never be a real configured tenant
  // (its teardown would purge the wildcard-admin audit chain).
  if (enabled() && (process.env.OPENWOP_STORAGE_DSN ?? '').startsWith('memory')) {
    log.warn('breakglass_on_nonshared_storage', {
      detail: 'OPENWOP_BREAKGLASS_ENABLED=true with memory:// storage — the single-use burn is per-instance, not global.',
    });
  }
  for (const envName of ['OPENWOP_BREAKGLASS_TENANT', 'OPENWOP_SUPERADMIN_TENANTS'] as const) {
    if ((process.env[envName] ?? '').split(',').map((t) => t.trim()).includes('host-admin')) {
      log.error('reserved_tenant_configured', { envName, detail: "'host-admin' is the reserved wildcard-admin audit chain — configuring it as a real tenant would let tenant teardown destroy that chain." });
    }
  }
  app.post('/v1/host/openwop-app/auth/break-glass', async (req, res, next) => {
    try {
      // Disabled ⇒ indistinguishable from a route that doesn't exist.
      if (!enabled()) {
        res.status(404).json({ error: 'not_found', message: 'Not found.' });
        return;
      }
      const ip = clientIp(req);
      const now = Date.now();
      // Cap the window map so an address-spraying client can't grow it
      // unboundedly (grade-pass SEC-C3).
      if (attemptTimes.size > 10_000) attemptTimes.clear();
      const times = (attemptTimes.get(ip) ?? []).filter((t) => now - t < WINDOW_MS);
      if (times.length >= MAX_ATTEMPTS) {
        throw new OpenwopError('rate_limited', 'Too many break-glass attempts. Try again later.', 429, {});
      }
      times.push(now);
      attemptTimes.set(ip, times);

      const tenantId = process.env.OPENWOP_BREAKGLASS_TENANT ?? '';
      const superadmins = (process.env.OPENWOP_SUPERADMIN_TENANTS ?? '').split(',').map((s) => s.trim());
      const parsed = parseTokenHash();
      const body = (req.body ?? {}) as { token?: unknown };
      const token = typeof body.token === 'string' ? body.token : '';
      const at = new Date().toISOString();
      const auditTenant = tenantId || 'host-admin';

      // Fail-closed config checks — audit the denial reason, tell the caller nothing specific.
      const deny = async (reason: string): Promise<never> => {
        log.warn('breakglass_denied', { reason, ip });
        await auditAndNotify('security.breakglass-denied', auditTenant, { reason, ip, at });
        throw new OpenwopError('unauthenticated', 'Break-glass login refused.', 401, {});
      };

      if (!parsed) return await deny('token_hash_unset_or_malformed');
      if (!tenantId) return await deny('tenant_unset');
      if (!superadmins.includes(tenantId)) return await deny('tenant_not_superadmin');
      if (!token || token.length < 16) return await deny('token_missing_or_short');
      if (!(await verifyToken(token, parsed))) return await deny('token_mismatch');

      // SINGLE-USE: CAS-claim the burn marker; a second use of the same token
      // loses the claim and is refused (rotate the env hash to re-arm).
      const hashKey = parsed.hash.toString('base64');
      const claimed = await burns.compareAndSwap(null, { hashKey, usedAt: at, ip });
      if (!claimed) return await deny('token_already_used');

      // Mint the short-TTL, non-refreshing superadmin-tenant session. The
      // subject is a fresh opaque break-glass principal (never a durable user).
      const nowS = Math.floor(now / 1000);
      const sid = base64urlEncode(randomBytes(18));
      const session: SessionPayload = {
        sid,
        tenantId,
        tier: 'user',
        subject: `breakglass:${sid}`,
        // ADR 0434 P4 / IDN-5 — break-glass deliberately does NOT restore the
        // operator's stored active workspace. An emergency session is a
        // narrowly-scoped, single-use, audited grant; silently widening it to
        // whatever workspace they last used would defeat that scoping. The
        // omission is intentional, not an oversight.
        personalTenant: tenantId,
        noRefresh: true, // the 10-minute window is HARD (grade-pass SEC-C2)
        iat: nowS,
        exp: nowS + SESSION_TTL_S,
      };
      // GRADE-PASS 2026-07-17 (SEC-C16): the SUCCESS audit is fail-closed —
      // the burn CAS just proved storage is up, so an unchainable login is
      // refused rather than granted invisibly. (Denial audits stay
      // best-effort; notification stays best-effort.)
      await appendAudit(tenantId, 'security.breakglass-login', { ip, at });
      setSessionCookie(res, signSession(session));
      log.warn('breakglass_login', { ip, tenantId });
      await notifyMembers(tenantId, { ip, at }, 'Break-glass login used');
      res.json({ ok: true, tenantId, expiresInSeconds: SESSION_TTL_S });
    } catch (err) {
      next(err);
    }
  });
}

/** Test seam — clear the in-memory attempt window. */
export function _resetBreakGlassAttempts(): void {
  attemptTimes.clear();
}
