/**
 * Sales Maps — region CATALOG (id + display name only; ADR 0282 §8).
 *
 * The picker-sized companion to worldBoundaries.ts: same 176 Natural Earth
 * countries, NO geometry — safe to import from other lazy chunks (the
 * Territories page's map-region field) without dragging the boundary data in.
 *
 * GENERATED FILE — do not hand-edit; re-run scripts/vendor-boundaries.mjs.
 */
export interface RegionCatalogEntry { id: string; name: string }

export const REGION_CATALOG: readonly RegionCatalogEntry[] = [
  {"id":"afg","name":"Afghanistan"},
  {"id":"ago","name":"Angola"},
  {"id":"alb","name":"Albania"},
  {"id":"are","name":"United Arab Emirates"},
  {"id":"arg","name":"Argentina"},
  {"id":"arm","name":"Armenia"},
  {"id":"atf","name":"French Southern and Antarctic Lands"},
  {"id":"aus","name":"Australia"},
  {"id":"aut","name":"Austria"},
  {"id":"aze","name":"Azerbaijan"},
  {"id":"bdi","name":"Burundi"},
  {"id":"bel","name":"Belgium"},
  {"id":"ben","name":"Benin"},
  {"id":"bfa","name":"Burkina Faso"},
  {"id":"bgd","name":"Bangladesh"},
  {"id":"bgr","name":"Bulgaria"},
  {"id":"bhs","name":"The Bahamas"},
  {"id":"bih","name":"Bosnia and Herzegovina"},
  {"id":"blr","name":"Belarus"},
  {"id":"blz","name":"Belize"},
  {"id":"bol","name":"Bolivia"},
  {"id":"bra","name":"Brazil"},
  {"id":"brn","name":"Brunei"},
  {"id":"btn","name":"Bhutan"},
  {"id":"bwa","name":"Botswana"},
  {"id":"caf","name":"Central African Republic"},
  {"id":"can","name":"Canada"},
  {"id":"che","name":"Switzerland"},
  {"id":"chl","name":"Chile"},
  {"id":"chn","name":"People's Republic of China"},
  {"id":"civ","name":"Ivory Coast"},
  {"id":"cmr","name":"Cameroon"},
  {"id":"cod","name":"Democratic Republic of the Congo"},
  {"id":"cog","name":"Republic of the Congo"},
  {"id":"col","name":"Colombia"},
  {"id":"cri","name":"Costa Rica"},
  {"id":"cub","name":"Cuba"},
  {"id":"cyn","name":"Turkish Republic of Northern Cyprus"},
  {"id":"cyp","name":"Cyprus"},
  {"id":"cze","name":"Czech Republic"},
  {"id":"deu","name":"Germany"},
  {"id":"dji","name":"Djibouti"},
  {"id":"dnk","name":"Denmark"},
  {"id":"dom","name":"Dominican Republic"},
  {"id":"dza","name":"Algeria"},
  {"id":"ecu","name":"Ecuador"},
  {"id":"egy","name":"Egypt"},
  {"id":"eri","name":"Eritrea"},
  {"id":"esp","name":"Spain"},
  {"id":"est","name":"Estonia"},
  {"id":"eth","name":"Ethiopia"},
  {"id":"fin","name":"Finland"},
  {"id":"fji","name":"Fiji"},
  {"id":"flk","name":"Falkland Islands"},
  {"id":"fra","name":"France"},
  {"id":"gab","name":"Gabon"},
  {"id":"gbr","name":"United Kingdom"},
  {"id":"geo","name":"Georgia"},
  {"id":"gha","name":"Ghana"},
  {"id":"gin","name":"Guinea"},
  {"id":"gmb","name":"The Gambia"},
  {"id":"gnb","name":"Guinea-Bissau"},
  {"id":"gnq","name":"Equatorial Guinea"},
  {"id":"grc","name":"Greece"},
  {"id":"grl","name":"Greenland"},
  {"id":"gtm","name":"Guatemala"},
  {"id":"guy","name":"Guyana"},
  {"id":"hnd","name":"Honduras"},
  {"id":"hrv","name":"Croatia"},
  {"id":"hti","name":"Haiti"},
  {"id":"hun","name":"Hungary"},
  {"id":"idn","name":"Indonesia"},
  {"id":"ind","name":"India"},
  {"id":"irl","name":"Ireland"},
  {"id":"irn","name":"Iran"},
  {"id":"irq","name":"Iraq"},
  {"id":"isl","name":"Iceland"},
  {"id":"isr","name":"Israel"},
  {"id":"ita","name":"Italy"},
  {"id":"jam","name":"Jamaica"},
  {"id":"jor","name":"Jordan"},
  {"id":"jpn","name":"Japan"},
  {"id":"kaz","name":"Kazakhstan"},
  {"id":"ken","name":"Kenya"},
  {"id":"kgz","name":"Kyrgyzstan"},
  {"id":"khm","name":"Cambodia"},
  {"id":"kor","name":"South Korea"},
  {"id":"kos","name":"Kosovo"},
  {"id":"kwt","name":"Kuwait"},
  {"id":"lao","name":"Laos"},
  {"id":"lbn","name":"Lebanon"},
  {"id":"lbr","name":"Liberia"},
  {"id":"lby","name":"Libya"},
  {"id":"lka","name":"Sri Lanka"},
  {"id":"lso","name":"Lesotho"},
  {"id":"ltu","name":"Lithuania"},
  {"id":"lux","name":"Luxembourg"},
  {"id":"lva","name":"Latvia"},
  {"id":"mar","name":"Morocco"},
  {"id":"mda","name":"Moldova"},
  {"id":"mdg","name":"Madagascar"},
  {"id":"mex","name":"Mexico"},
  {"id":"mkd","name":"North Macedonia"},
  {"id":"mli","name":"Mali"},
  {"id":"mmr","name":"Myanmar"},
  {"id":"mne","name":"Montenegro"},
  {"id":"mng","name":"Mongolia"},
  {"id":"moz","name":"Mozambique"},
  {"id":"mrt","name":"Mauritania"},
  {"id":"mwi","name":"Malawi"},
  {"id":"mys","name":"Malaysia"},
  {"id":"nam","name":"Namibia"},
  {"id":"ncl","name":"New Caledonia"},
  {"id":"ner","name":"Niger"},
  {"id":"nga","name":"Nigeria"},
  {"id":"nic","name":"Nicaragua"},
  {"id":"nld","name":"Netherlands"},
  {"id":"nor","name":"Norway"},
  {"id":"npl","name":"Nepal"},
  {"id":"nzl","name":"New Zealand"},
  {"id":"omn","name":"Oman"},
  {"id":"pak","name":"Pakistan"},
  {"id":"pan","name":"Panama"},
  {"id":"per","name":"Peru"},
  {"id":"phl","name":"Philippines"},
  {"id":"png","name":"Papua New Guinea"},
  {"id":"pol","name":"Poland"},
  {"id":"pri","name":"Puerto Rico"},
  {"id":"prk","name":"North Korea"},
  {"id":"prt","name":"Portugal"},
  {"id":"pry","name":"Paraguay"},
  {"id":"psx","name":"Palestine"},
  {"id":"qat","name":"Qatar"},
  {"id":"rou","name":"Romania"},
  {"id":"rus","name":"Russia"},
  {"id":"rwa","name":"Rwanda"},
  {"id":"sah","name":"Western Sahara"},
  {"id":"sau","name":"Saudi Arabia"},
  {"id":"sdn","name":"Sudan"},
  {"id":"sds","name":"South Sudan"},
  {"id":"sen","name":"Senegal"},
  {"id":"slb","name":"Solomon Islands"},
  {"id":"sle","name":"Sierra Leone"},
  {"id":"slv","name":"El Salvador"},
  {"id":"sol","name":"Somaliland"},
  {"id":"som","name":"Somalia"},
  {"id":"srb","name":"Serbia"},
  {"id":"sur","name":"Suriname"},
  {"id":"svk","name":"Slovakia"},
  {"id":"svn","name":"Slovenia"},
  {"id":"swe","name":"Sweden"},
  {"id":"swz","name":"Eswatini"},
  {"id":"syr","name":"Syria"},
  {"id":"tcd","name":"Chad"},
  {"id":"tgo","name":"Togo"},
  {"id":"tha","name":"Thailand"},
  {"id":"tjk","name":"Tajikistan"},
  {"id":"tkm","name":"Turkmenistan"},
  {"id":"tls","name":"East Timor"},
  {"id":"tto","name":"Trinidad and Tobago"},
  {"id":"tun","name":"Tunisia"},
  {"id":"tur","name":"Turkey"},
  {"id":"twn","name":"Taiwan"},
  {"id":"tza","name":"Tanzania"},
  {"id":"uga","name":"Uganda"},
  {"id":"ukr","name":"Ukraine"},
  {"id":"ury","name":"Uruguay"},
  {"id":"usa","name":"United States of America"},
  {"id":"uzb","name":"Uzbekistan"},
  {"id":"ven","name":"Venezuela"},
  {"id":"vnm","name":"Vietnam"},
  {"id":"vut","name":"Vanuatu"},
  {"id":"yem","name":"Yemen"},
  {"id":"zaf","name":"South Africa"},
  {"id":"zmb","name":"Zambia"},
  {"id":"zwe","name":"Zimbabwe"},
];
