/**
 * ADR 0591 P1 — the durable effect escape ledger.
 *
 * THE TEST THAT MATTERS IS THE FIRST ONE, and it exists because the previous
 * instrument failed exactly here. `invocation_log` is written with
 * `INSERT OR REPLACE` over a primary key containing `attempt`, and `attempt` is
 * a constant on this host (`executor.ts:990` — the 1-based one-shot stub). So a
 * second escape of the same identity OVERWROTE the first row, and
 * `COUNT(*) GROUP BY invocation_id` returned 1 whether dedup worked or was
 * entirely broken. Measured, not theorised:
 *
 *   INSERT OR REPLACE … VALUES ('r1','effect',1,'ord0','first','t1');
 *   INSERT OR REPLACE … VALUES ('r1','effect',1,'ord0','second','t2');
 *   → 1 row, surviving result 'second'
 *
 * An instrument whose PASS is ambiguous does not witness the property; it
 * certifies the property's absence. So the assertion below is not "the ledger
 * stores rows" — it is **two escapes of ONE identity produce TWO rows**. If
 * that ever collapses to one, the RFC 0158 §C.7 witness silently becomes
 * vacuous again, and this test is the tripwire.
 *
 * THE REPLACEMENT REINTRODUCED THE FAMILY ONCE ALREADY, which is why the
 * fourth test below exists. The first draft of this ledger took an `escapeSeq`
 * from the caller and put it in the primary key. Any caller-supplied sequence
 * is process-local, and §C.7 is driven by KILLING the process — so the resumed
 * process re-appends the same identity at seq 0 and collides with the pre-kill
 * row. Measured against that draft:
 *
 *   process A: append(r/n/ord0, seq 0) → 1 row
 *   process B: append(r/n/ord0, seq 0) → UNIQUE constraint failed; count = 1
 *
 * Unswallowed that throws on the ALLOW branch of `assertEffectAllowed` (a
 * durability instrument breaking production egress); swallowed, the count
 * freezes at 1 — the very collapse this table replaced `invocation_log` to
 * escape. The row id is now generated by the store, so no append can address
 * an existing row.
 */
import { describe, expect, it } from 'vitest';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openStorage } from '../src/storage/index.js';

// A fresh on-disk db per test: `memory://` mints a new sqlite per openStorage()
// call, so a shared in-memory handle would not be shared anyway, and a real
// file keeps the migration path (mig 42) genuinely exercised.
async function freshStorage() {
  const dir = mkdtempSync(join(tmpdir(), 'adr0591-'));
  return openStorage(`sqlite://${join(dir, 'ledger.db')}`);
}

describe('ADR 0591 — effect escape ledger', () => {
  it('records a SECOND escape of the same identity as a SECOND row (the anti-collapse invariant)', async () => {
    const storage = await freshStorage();
    const base = { runId: 'r1', nodeId: 'effect', invocationId: 'ord0', effectKind: 'http' };

    await storage.appendEffectEscape({ ...base, createdAt: '2026-08-21T00:00:00.000Z' });
    await storage.appendEffectEscape({ ...base, createdAt: '2026-08-21T00:00:01.000Z' });

    const rows = await storage.listEffectEscapes('r1');
    expect(rows).toHaveLength(1); // one identity…
    // …that escaped TWICE. This is the number `invocation_log` could not produce.
    expect(rows[0]!.count).toBe(2);
    expect(rows[0]!.invocationId).toBe('ord0');
  });

  it('counts PER IDENTITY, not as a per-run scalar (RFC 0158 §C.7:162)', async () => {
    // The scalar seam (`replay/effect-count`) equals the per-identity count only
    // when a graph holds exactly one identity — a property of the fixture, not
    // of the host. Two identities is the case that separates the instruments.
    const storage = await freshStorage();
    const at = '2026-08-21T00:00:00.000Z';
    await storage.appendEffectEscape({ runId: 'r2', nodeId: 'a', invocationId: 'ordA', effectKind: 'http', createdAt: at });
    await storage.appendEffectEscape({ runId: 'r2', nodeId: 'b', invocationId: 'ordB', effectKind: 'http', createdAt: at });
    await storage.appendEffectEscape({ runId: 'r2', nodeId: 'b', invocationId: 'ordB', effectKind: 'http', createdAt: at });

    const byId = Object.fromEntries((await storage.listEffectEscapes('r2')).map((r) => [r.invocationId, r.count]));
    expect(byId).toEqual({ ordA: 1, ordB: 2 });
    // A scalar would report 3 here and be unable to say WHICH identity doubled.
  });

  it('is scoped per run — one run cannot inflate another run’s count', async () => {
    const storage = await freshStorage();
    const at = '2026-08-21T00:00:00.000Z';
    await storage.appendEffectEscape({ runId: 'r3', nodeId: 'n', invocationId: 'ord0', effectKind: 'http', createdAt: at });
    await storage.appendEffectEscape({ runId: 'r4', nodeId: 'n', invocationId: 'ord0', effectKind: 'http', createdAt: at });

    expect(await storage.listEffectEscapes('r3')).toEqual([{ invocationId: 'ord0', nodeId: 'n', count: 1 }]);
    expect(await storage.listEffectEscapes('r4')).toEqual([{ invocationId: 'ord0', nodeId: 'n', count: 1 }]);
  });

  it('returns an empty list for a run with no escapes — absent, not zero-row-shaped garbage', async () => {
    const storage = await freshStorage();
    expect(await storage.listEffectEscapes('never-ran')).toEqual([]);
  });

  it('retires with the run — the rows do not outlive deleteRun (GEN-5)', async () => {
    // The GEN-5 drift guard only compares its own mirror SET against the
    // schema; it never executes a delete. So updating that set is sufficient to
    // make the guard green while the real cascade is still missing — the
    // "ratchet polices a spelling, not the invariant" shape. This asserts the
    // actual behaviour: the ledger is run-keyed with no tenant_id, so if it is
    // not cascaded its rows survive tenant teardown as orphans.
    const storage = await freshStorage();
    const at = '2026-08-21T00:00:00.000Z';
    await storage.appendEffectEscape({ runId: 'r6', nodeId: 'n', invocationId: 'ord0', effectKind: 'http', createdAt: at });
    expect(await storage.listEffectEscapes('r6')).toHaveLength(1);

    await storage.deleteRun('r6');

    expect(await storage.listEffectEscapes('r6')).toEqual([]);
  });

  it('survives a POST-KILL re-append of the same identity — no key the caller can collide', async () => {
    // The §C.7 shape specifically: the pre-kill process recorded an escape, the
    // process that resumed the run records another for the SAME identity, and
    // its bookkeeping restarted from scratch. Nothing about the second append
    // can distinguish itself from the first — same run, node, invocation, kind.
    // That must be two rows and must not throw; the earlier draft did both
    // wrong (see the docblock measurement).
    const storage = await freshStorage();
    const identical = {
      runId: 'r5', nodeId: 'notify', invocationId: 'ord0',
      effectKind: 'http', createdAt: '2026-08-21T00:00:00.000Z',
    };

    await storage.appendEffectEscape({ ...identical }); // pre-kill
    await expect(storage.appendEffectEscape({ ...identical })).resolves.toBeUndefined(); // post-resume

    expect(await storage.listEffectEscapes('r5')).toEqual([
      { invocationId: 'ord0', nodeId: 'notify', count: 2 },
    ]);
  });
});
