/**
 * The dashboard tile registry (ADR 0375 Phase 2) — the ONE composition root for
 * tiles, sibling to the backend `BACKEND_FEATURES`. Each contributing feature's
 * tile module is imported here EAGERLY (metadata only; the component itself is a
 * `lazy(...)`), so every registered tile is known at first paint without loading
 * any feature page.
 *
 * This module is imported by `DashboardPage`, NEVER by `chrome/features.tsx`
 * (which imports `DashboardPage` as the route element) — keeping the two apart
 * is what avoids the chrome/features ⇄ DashboardPage cycle (architect-corrected).
 *
 * Phase 2 ships two work-hub tiles to prove the pipeline end-to-end; Phase 3
 * fills the catalog (business-metrics tiles + the rest), each co-located with
 * (or near) its owning feature and appended here.
 */
import { lazy } from 'react';
import {
  ActivityIcon, MessageSquareIcon, CheckSquareIcon, ClockIcon, FileTextIcon,
  BarChartIcon, BriefcaseIcon, MegaphoneIcon, FilterIcon, StarIcon,
  ListIcon, InboxIcon, BellIcon, FolderIcon, BotIcon, ZapIcon, HeartIcon,
  UsersIcon, BookOpenIcon, BoxesIcon, GlobeIcon, SparklesIcon, ImageIcon, DatabaseIcon, PlugIcon,
  CalendarIcon,
} from '../../ui/icons/index.js';
import type { DashboardTileDef } from './tileTypes.js';

export const ALL_DASHBOARD_TILES: DashboardTileDef[] = [
  {
    id: 'active-runs',
    label: 'Active runs',
    labelKey: 'tileActiveRuns',
    descriptionKey: 'tileActiveRunsDesc',
    icon: ActivityIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: true,
    defaultOrder: 0,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/ActiveRunsTile.js')),
  },
  {
    id: 'recent-conversations',
    label: 'Recent conversations',
    labelKey: 'tileRecentConversations',
    descriptionKey: 'tileRecentConversationsDesc',
    icon: MessageSquareIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: true,
    defaultOrder: 10,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/RecentConversationsTile.js')),
  },

  // ── Phase 3: work-hub tiles ────────────────────────────────────────────────
  {
    // Admin-tier: the rows link to /boards, a core admin-tier route. Default-on
    // for admins (a work-hub staple); caller-scoped (no org).
    id: 'todos',
    label: 'My to-dos',
    labelKey: 'tileTodos',
    descriptionKey: 'tileTodosDesc',
    icon: CheckSquareIcon,
    category: 'Work',
    requiredTier: 'admin',
    defaultEnabled: true,
    defaultOrder: 20,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/TodosTile.js')),
  },
  {
    // Org-scoped → default OFF (opt-in via the picker; keeps first-paint reads low).
    id: 'scheduled-agents',
    label: 'Upcoming scheduled agents',
    labelKey: 'tileScheduledAgents',
    descriptionKey: 'tileScheduledAgentsDesc',
    icon: ClockIcon,
    category: 'Work',
    requiredTier: 'workspace',
    owningFeatureToggle: 'scheduled-agent-chats',
    defaultEnabled: false,
    defaultOrder: 30,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/ScheduledAgentsTile.js')),
  },
  {
    // ADR 0577 — a read-only PROJECTION of a scheduled agent chat's latest
    // assistant turn (never a chat surface). Opt-in from the gallery.
    id: 'ai-briefing',
    label: 'AI briefing',
    labelKey: 'tileAiBriefing',
    descriptionKey: 'tileAiBriefingDesc',
    icon: SparklesIcon,
    category: 'AI',
    requiredTier: 'workspace',
    owningFeatureToggle: 'scheduled-agent-chats',
    defaultEnabled: false,
    defaultOrder: 31,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/AiBriefingTile.js')),
  },
  {
    id: 'recent-documents',
    label: 'Recent documents',
    labelKey: 'tileRecentDocuments',
    descriptionKey: 'tileRecentDocumentsDesc',
    icon: FileTextIcon,
    category: 'Work',
    requiredTier: 'workspace',
    owningFeatureToggle: 'documents',
    defaultEnabled: false,
    defaultOrder: 40,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/RecentDocumentsTile.js')),
  },

  // ── Phase 3: business-metrics tiles (admin, each behind its owning toggle,
  //    all default OFF — opt-in via the picker) ───────────────────────────────
  {
    id: 'crm-pipeline',
    label: 'CRM pipeline',
    labelKey: 'tileCrmPipeline',
    descriptionKey: 'tileCrmPipelineDesc',
    icon: BarChartIcon,
    category: 'Business',
    requiredTier: 'admin',
    owningFeatureToggle: 'crm',
    defaultEnabled: false,
    defaultOrder: 50,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/CrmPipelineTile.js')),
  },
  {
    id: 'commerce-summary',
    label: 'Commerce',
    labelKey: 'tileCommerce',
    descriptionKey: 'tileCommerceDesc',
    icon: BriefcaseIcon,
    category: 'Business',
    requiredTier: 'admin',
    owningFeatureToggle: 'commerce',
    defaultEnabled: false,
    defaultOrder: 60,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/CommerceSummaryTile.js')),
  },
  {
    id: 'campaign-kpis',
    label: 'Campaign KPIs',
    labelKey: 'tileCampaign',
    descriptionKey: 'tileCampaignDesc',
    icon: MegaphoneIcon,
    category: 'Business',
    requiredTier: 'admin',
    owningFeatureToggle: 'campaign-intel',
    defaultEnabled: false,
    defaultOrder: 70,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/CampaignKpisTile.js')),
  },
  {
    id: 'funnel-conversion',
    label: 'Funnel conversion',
    labelKey: 'tileFunnel',
    descriptionKey: 'tileFunnelDesc',
    icon: FilterIcon,
    category: 'Business',
    requiredTier: 'admin',
    owningFeatureToggle: 'funnels',
    defaultEnabled: false,
    defaultOrder: 80,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/FunnelConversionTile.js')),
  },
  {
    id: 'top-priorities',
    label: 'Top priorities',
    labelKey: 'tilePriorities',
    descriptionKey: 'tilePrioritiesDesc',
    icon: StarIcon,
    category: 'Business',
    requiredTier: 'admin',
    owningFeatureToggle: 'priority-matrix',
    defaultEnabled: false,
    defaultOrder: 90,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/TopPrioritiesTile.js')),
  },
  // ── ADR 0377 Wave 1: work-hub + business catalog (all opt-in; tile tier =
  //    the tier of the page each deep-links to — architect pin) ──────────────
  {
    id: 'approvals-inbox',
    label: 'Approvals inbox',
    labelKey: 'tileApprovals',
    descriptionKey: 'tileApprovalsDesc',
    icon: InboxIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: true,
    defaultOrder: 12,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/ApprovalsInboxTile.js')),
  },
  {
    id: 'notifications',
    label: 'Notifications',
    labelKey: 'tileNotifications',
    descriptionKey: 'tileNotificationsDesc',
    icon: BellIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: true,
    defaultOrder: 14,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/NotificationsTile.js')),
  },
  {
    id: 'my-projects',
    label: 'My projects',
    labelKey: 'tileProjects',
    descriptionKey: 'tileProjectsDesc',
    icon: FolderIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: false,
    defaultOrder: 120,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/MyProjectsTile.js')),
  },
  {
    id: 'agent-fleet',
    label: 'Agent fleet',
    labelKey: 'tileFleet',
    descriptionKey: 'tileFleetDesc',
    icon: BotIcon,
    category: 'AI',
    requiredTier: 'workspace',
    defaultEnabled: false,
    defaultOrder: 130,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/AgentFleetTile.js')),
  },
  {
    id: 'task-deck',
    label: 'Task deck',
    labelKey: 'tileTaskDeck',
    descriptionKey: 'tileTaskDeckDesc',
    icon: ListIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: false,
    defaultOrder: 140,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/TaskDeckTile.js')),
  },
  {
    id: 'strategy-health',
    label: 'Strategy health',
    labelKey: 'tileStrategy',
    descriptionKey: 'tileStrategyDesc',
    icon: ActivityIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'strategy',
    defaultEnabled: false,
    defaultOrder: 150,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/StrategyHealthTile.js')),
  },
  {
    id: 'csm-health',
    label: 'Account health',
    labelKey: 'tileCsm',
    descriptionKey: 'tileCsmDesc',
    icon: HeartIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'csm',
    defaultEnabled: false,
    defaultOrder: 160,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/CsmHealthTile.js')),
  },
  {
    id: 'advisory-boards',
    label: 'Advisory boards',
    labelKey: 'tileAdvisory',
    descriptionKey: 'tileAdvisoryDesc',
    icon: UsersIcon,
    category: 'Work',
    requiredTier: 'workspace',
    owningFeatureToggle: 'advisory-board',
    defaultEnabled: false,
    defaultOrder: 170,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/AdvisoryBoardsTile.js')),
  },
  {
    id: 'recent-notebooks',
    label: 'Recent notebooks',
    labelKey: 'tileNotebooks',
    descriptionKey: 'tileNotebooksDesc',
    icon: BookOpenIcon,
    category: 'Content',
    requiredTier: 'workspace',
    owningFeatureToggle: 'notebooks',
    defaultEnabled: false,
    defaultOrder: 180,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/RecentNotebooksTile.js')),
  },
  {
    id: 'workforce-ops',
    label: 'Workforces',
    labelKey: 'tileWorkforces',
    descriptionKey: 'tileWorkforcesDesc',
    icon: BoxesIcon,
    category: 'Operations',
    requiredTier: 'admin',
    defaultEnabled: false,
    defaultOrder: 190,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/WorkforceOpsTile.js')),
  },
  {
    id: 'site-traffic',
    label: 'Site traffic',
    labelKey: 'tileTraffic',
    descriptionKey: 'tileTrafficDesc',
    icon: GlobeIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'analytics',
    defaultEnabled: false,
    defaultOrder: 200,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/SiteTrafficTile.js')),
  },
  {
    id: 'ai-spend',
    label: 'AI spend',
    labelKey: 'tileAiSpend',
    descriptionKey: 'tileAiSpendDesc',
    icon: SparklesIcon,
    category: 'AI',
    requiredTier: 'admin',
    owningFeatureToggle: 'usage-analytics',
    defaultEnabled: false,
    defaultOrder: 210,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/AiSpendTile.js')),
  },
  {
    id: 'ad-spend-roas',
    label: 'Ad spend & ROAS',
    labelKey: 'tileAdSpend',
    descriptionKey: 'tileAdSpendDesc',
    icon: MegaphoneIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'campaign-connectors',
    defaultEnabled: false,
    defaultOrder: 220,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/AdSpendRoasTile.js')),
  },
  {
    id: 'commissions',
    label: 'Commissions',
    labelKey: 'tileCommissions',
    descriptionKey: 'tileCommissionsDesc',
    icon: BriefcaseIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'sales-commissions',
    defaultEnabled: false,
    defaultOrder: 230,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/CommissionsTile.js')),
  },
  {
    id: 'model-leaderboard',
    label: 'Model leaderboard',
    labelKey: 'tileLeaderboard',
    descriptionKey: 'tileLeaderboardDesc',
    icon: StarIcon,
    category: 'AI',
    requiredTier: 'admin',
    owningFeatureToggle: 'evals',
    defaultEnabled: false,
    defaultOrder: 240,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/ModelLeaderboardTile.js')),
  },
  {
    id: 'live-promotions',
    label: 'Live promotions',
    labelKey: 'tilePromotions',
    descriptionKey: 'tilePromotionsDesc',
    icon: ZapIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'promotions',
    defaultEnabled: false,
    defaultOrder: 250,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/LivePromotionsTile.js')),
  },
  {
    id: 'suggested-automations',
    label: 'Suggested automations',
    labelKey: 'tileSuggestions',
    descriptionKey: 'tileSuggestionsDesc',
    icon: SparklesIcon,
    category: 'AI',
    requiredTier: 'admin',
    owningFeatureToggle: 'ambient-work-graph',
    defaultEnabled: false,
    defaultOrder: 260,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/SuggestedAutomationsTile.js')),
  },
  {
    id: 'campaigns-in-flight',
    label: 'Campaigns in flight',
    labelKey: 'tileCampaignsFlight',
    descriptionKey: 'tileCampaignsFlightDesc',
    icon: MegaphoneIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'campaign-orchestration',
    defaultEnabled: false,
    defaultOrder: 270,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/CampaignsInFlightTile.js')),
  },
  {
    id: 'recent-media',
    label: 'Recent media',
    labelKey: 'tileMedia',
    descriptionKey: 'tileMediaDesc',
    icon: ImageIcon,
    category: 'Content',
    requiredTier: 'admin',
    owningFeatureToggle: 'media',
    defaultEnabled: false,
    defaultOrder: 280,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/RecentMediaTile.js')),
  },
  {
    id: 'kb-overview',
    label: 'Knowledge base',
    labelKey: 'tileKb',
    descriptionKey: 'tileKbDesc',
    icon: DatabaseIcon,
    category: 'Content',
    requiredTier: 'admin',
    owningFeatureToggle: 'kb',
    defaultEnabled: false,
    defaultOrder: 290,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/KbOverviewTile.js')),
  },
  {
    id: 'deal-registrations',
    label: 'Deal registrations',
    labelKey: 'tileDeals',
    descriptionKey: 'tileDealsDesc',
    icon: BriefcaseIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'dealers',
    defaultEnabled: false,
    defaultOrder: 300,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/DealRegistrationsTile.js')),
  },
  // ── ADR 0377 Wave 2: chart tiles (TileBars / Sparkline / delta — all opt-in) ──
  {
    id: 'pipeline-trend',
    label: 'Pipeline trend',
    labelKey: 'tilePipelineTrend',
    descriptionKey: 'tilePipelineTrendDesc',
    icon: BarChartIcon,
    category: 'Business',
    requiredTier: 'admin',
    owningFeatureToggle: 'crm',
    defaultEnabled: false,
    defaultOrder: 310,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/PipelineTrendTile.js')),
  },
  {
    id: 'bi-metric',
    label: 'Business metric',
    labelKey: 'tileBiMetric',
    descriptionKey: 'tileBiMetricDesc',
    icon: BarChartIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'bi',
    defaultEnabled: false,
    defaultOrder: 315,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/BiMetricTile.js')),
  },
  {
    id: 'funnel-daily',
    label: 'Funnel daily',
    labelKey: 'tileFunnelDaily',
    descriptionKey: 'tileFunnelDailyDesc',
    icon: FilterIcon,
    category: 'Business',
    requiredTier: 'admin',
    owningFeatureToggle: 'funnels',
    defaultEnabled: false,
    defaultOrder: 320,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/FunnelDailyTile.js')),
  },
  {
    id: 'spend-pacing',
    label: 'Spend pacing',
    labelKey: 'tileSpendPacing',
    descriptionKey: 'tileSpendPacingDesc',
    icon: MegaphoneIcon,
    category: 'Business',
    requiredTier: 'admin',
    owningFeatureToggle: 'campaign-intel',
    defaultEnabled: false,
    defaultOrder: 330,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/SpendPacingTile.js')),
  },
  {
    id: 'platform-performance',
    label: 'Platform performance',
    labelKey: 'tilePlatformPerf',
    descriptionKey: 'tilePlatformPerfDesc',
    icon: MegaphoneIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'campaign-connectors',
    defaultEnabled: false,
    defaultOrder: 340,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/PlatformPerformanceTile.js')),
  },
  {
    id: 'cost-by-model',
    label: 'Cost by model',
    labelKey: 'tileCostByModel',
    descriptionKey: 'tileCostByModelDesc',
    icon: SparklesIcon,
    category: 'AI',
    requiredTier: 'admin',
    owningFeatureToggle: 'usage-analytics',
    defaultEnabled: false,
    defaultOrder: 350,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/CostByModelTile.js')),
  },
  {
    id: 'content-status',
    label: 'Content status',
    labelKey: 'tileContentStatus',
    descriptionKey: 'tileContentStatusDesc',
    icon: FileTextIcon,
    category: 'Content',
    requiredTier: 'admin',
    owningFeatureToggle: 'cms',
    defaultEnabled: false,
    defaultOrder: 360,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/ContentStatusTile.js')),
  },
  {
    id: 'production-status',
    label: 'Production status',
    labelKey: 'tileProductionStatus',
    descriptionKey: 'tileProductionStatusDesc',
    icon: BoxesIcon,
    category: 'Operations',
    requiredTier: 'workspace',
    owningFeatureToggle: 'production',
    defaultEnabled: false,
    defaultOrder: 370,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/ProductionStatusTile.js')),
  },
  {
    id: 'quota-attainment',
    label: 'Quota attainment',
    labelKey: 'tileAttainment',
    descriptionKey: 'tileAttainmentDesc',
    icon: BarChartIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'territories',
    defaultEnabled: false,
    defaultOrder: 380,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/QuotaAttainmentTile.js')),
  },
  {
    id: 'health-distribution',
    label: 'Health distribution',
    labelKey: 'tileHealthDist',
    descriptionKey: 'tileHealthDistDesc',
    icon: HeartIcon,
    category: 'Business',
    requiredTier: 'workspace',
    owningFeatureToggle: 'csm',
    defaultEnabled: false,
    defaultOrder: 390,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/HealthDistributionTile.js')),
  },
  // ── ADR 0377 Wave 3: interaction types (shortcut / resume / agenda / workload) ──
  {
    id: 'quick-create',
    label: 'Shortcuts',
    labelKey: 'tileQuickCreate',
    descriptionKey: 'tileQuickCreateDesc',
    icon: ZapIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: true,
    defaultOrder: -10,
    defaultSize: 'full',
    resizable: true,
    component: lazy(() => import('./tiles/QuickCreateTile.js')),
  },
  {
    id: 'continue-working',
    label: 'Continue working',
    labelKey: 'tileContinue',
    descriptionKey: 'tileContinueDesc',
    icon: FileTextIcon,
    category: 'Work',
    requiredTier: 'workspace',
    owningFeatureToggle: 'documents',
    defaultEnabled: true,
    defaultOrder: 16,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/ContinueWorkingTile.js')),
  },
  {
    id: 'upcoming-agenda',
    label: 'Upcoming',
    labelKey: 'tileAgenda',
    descriptionKey: 'tileAgendaDesc',
    icon: CalendarIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: false,
    defaultOrder: 420,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/UpcomingAgendaTile.js')),
  },
  {
    id: 'team-workload',
    label: 'Team workload',
    labelKey: 'tileWorkload',
    descriptionKey: 'tileWorkloadDesc',
    icon: UsersIcon,
    category: 'Operations',
    requiredTier: 'admin',
    defaultEnabled: false,
    defaultOrder: 430,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/TeamWorkloadTile.js')),
  },
  // ── ADR 0377 Wave 4: admin-ops health (resolved: admin-tier tiles in the ONE
  //    catalog — tier-gating already achieves MyndHyve's separate-tier intent) ──
  {
    id: 'connection-health',
    label: 'Connection health',
    labelKey: 'tileConnections',
    descriptionKey: 'tileConnectionsDesc',
    icon: PlugIcon,
    category: 'Operations',
    requiredTier: 'admin',
    owningFeatureToggle: 'connections',
    defaultEnabled: false,
    defaultOrder: 440,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/ConnectionHealthTile.js')),
  },
  {
    id: 'plugin-health',
    label: 'Plugin health',
    labelKey: 'tilePlugins',
    descriptionKey: 'tilePluginsDesc',
    icon: BoxesIcon,
    category: 'Operations',
    requiredTier: 'admin',
    owningFeatureToggle: 'ui-plugins',
    defaultEnabled: false,
    defaultOrder: 450,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/PluginHealthTile.js')),
  },
  {
    // The one tile with dashboard-owned content (its own subject-scoped note
    // row — see PersonalNoteTile). Closed the Wave-3 deferral 2026-07-16.
    id: 'personal-note',
    label: 'Personal note',
    labelKey: 'tileNote',
    descriptionKey: 'tileNoteDesc',
    icon: FileTextIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: false,
    defaultOrder: 460,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/PersonalNoteTile.js')),
  },
  {
    // The Wave-3 deferral closed (2026-07-17): the channel list now carries the
    // caller's ADR 0192 D6 read-marker counts server-side — one existing call.
    id: 'mentions-inbox',
    label: 'Mentions',
    labelKey: 'tileMentions',
    descriptionKey: 'tileMentionsDesc',
    icon: BellIcon,
    category: 'Work',
    requiredTier: 'workspace',
    defaultEnabled: false,
    defaultOrder: 470,
    defaultSize: 'half',
    resizable: true,
    component: lazy(() => import('./tiles/MentionsInboxTile.js')),
  },
  {
    id: 'kicktodo-today',
    label: 'KickTodo · Today',
    labelKey: 'tileKicktodoToday',
    descriptionKey: 'tileKicktodoTodayDesc',
    icon: CheckSquareIcon,
    category: 'Work',
    requiredTier: 'workspace',
    owningFeatureToggle: 'kicktodo-core',
    defaultEnabled: false,
    defaultOrder: 42,
    defaultSize: 'half',
    resizable: false,
    component: lazy(() => import('./tiles/KickTodoTodayTile.js')),
  },
  {
    id: 'kicktodo-progress',
    label: 'KickTodo · Progress',
    labelKey: 'tileKicktodoProgress',
    descriptionKey: 'tileKicktodoProgressDesc',
    icon: BarChartIcon,
    category: 'Work',
    requiredTier: 'workspace',
    owningFeatureToggle: 'kicktodo-core',
    defaultEnabled: false,
    defaultOrder: 43,
    defaultSize: 'half',
    resizable: false,
    component: lazy(() => import('./tiles/KickTodoProgressTile.js')),
  },
];

/** The default layout derived from the registry — the zero-write first-paint
 *  layout when the user has none saved. */
export function defaultLayoutFrom(tiles: readonly DashboardTileDef[]): { id: string; order: number; size: 'half' | 'full'; enabled: boolean }[] {
  return tiles.map((t) => ({ id: t.id, order: t.defaultOrder, size: t.defaultSize, enabled: t.defaultEnabled }));
}
