/**
 * Agent workflow composition — the TWO lanes over one shared pipeline
 * (ADR 0369 §6 + ADR 0473):
 *
 *  - `openwop:workflows.propose` (ADR 0473 — the DEFAULT lane): compose a
 *    bespoke definition, register it as a TRANSIENT draft (catalog-hidden,
 *    `generatedBy: agent:<id>`, builder-editable at /builder/<id>), and HOLD it
 *    on a `composed-workflow` PendingApproval. NOTHING runs until a human
 *    claims — this tool takes no `StartRunDeps`, so there is structurally no
 *    code path from propose to execution.
 *  - `openwop:workflows.compose-and-run` (ADR 0369 §6 — the AUTONOMOUS lane,
 *    superseded as the default by ADR 0473): compose, register, and run
 *    immediately. For explicitly-granted headless agents where a human is not
 *    in the loop by design. Still zero-granted by default.
 *
 * The shared safety argument — there is NO special path:
 *  - the candidate validates against the workflow-definition schema BEFORE
 *    anything is stored (invalid ⇒ tool error, nothing registered);
 *  - capability-gated node types are refused with the SAME rule as
 *    `POST /v1/runs` (`capabilityGatedTypeIdRefusal` — exported from the runs
 *    route so the two gates can never drift);
 *  - execution (immediate or approved) rides the shared `startWorkflowRun`
 *    recipe (replay/fork/observability inherited unchanged); approval gates,
 *    governance, and budgets all apply because it IS an ordinary run;
 *  - promotion to a SAVED workflow stays a USER act (the ADR 0369 §5 verb,
 *    gated on a successful run) — neither lane can mint catalog entries.
 *
 * Approval integrity (ADR 0473): the proposal pins `definitionHash` (SHA-256
 * over the canonical sorted-key JSON). The decide handler re-verifies the hash
 * AFTER its CAS — a builder edit racing the claim reopens the approval instead
 * of running an unreviewed definition (approve-what-you-see, server-enforced).
 *
 * Both tools register at the CORE level via `registerFeatureAgentTool` and are
 * granted per-agent through pack manifests / the ADR 0104 allowlist overrides
 * (default-deny) — never hard-wired to a named agent.
 *
 * Abuse bound (ADR 0369 OQ4): a per-tenant cap on LIVE transient definitions
 * generated by agents (`OPENWOP_AGENT_TRANSIENT_WORKFLOWS_MAX`, default 25) —
 * a runaway agent must not flood the registry/ownership/approval stores.
 */

import { randomUUID } from 'node:crypto';
import { registerFeatureAgentTool } from './agentToolProvider.js';
import { validateWorkflowDefinition, WORKFLOW_ID_PATTERN } from './workflowDefinitionValidation.js';
import { capabilityGatedTypeIdRefusal } from '../routes/runs.js';
import { registerWorkflow, registerWorkflowDurable, getRegisteredWorkflowAsync } from './workflowsRegistry.js';
import { withLifecycle, withHostLifecycle, lifecycleOf } from './workflowLifecycle.js';
import { recordOwnership, listOwned } from './workflowOwnership.js';
import { startWorkflowRun, type StartRunDeps } from './runStarter.js';
import {
  createComposedWorkflowApproval,
  registerComposedWorkflowApprovalHandler,
  getApproval,
  resolveApproval,
  reopenApproval,
  attachComposedDecision,
  listPendingApprovalsByKind,
  listApprovalsByKindAndStatus,
} from './approvalService.js';
import { getRetentionHold } from './runRetentionSweeper.js';
import { definitionHashOf } from './definitionHash.js';
import { sanitizeFreeTextDeep } from '../byok/textRedaction.js';
import { staticCostFloor } from './workflowCostEstimate.js';
import { recordRevision } from './workflowRevisions.js';
import { emitReviewUpdatedSignal } from '../notifications/notify.js';
import { claimApproval, type ApprovalDecisionDeps } from './approvalDecision.js';
import {
  getProposalAutoApprovePolicy,
  policyDeciderRef,
  AUTO_APPROVABLE_ROLES,
} from './workflowProposalPolicy.js';
import { nodeRoleMap, findUnknownTypeIds } from './nodeCatalogBuilder.js';
import { assertNoDisabledPacks } from './packEnablement.js';
import { OpenwopError } from '../types.js';
import type { WorkflowDefinition } from '../executor/types.js';
import { createLogger } from '../observability/logger.js';

export { definitionHashOf } from './definitionHash.js';

const log = createLogger('host.workflowComposeTool');

export const COMPOSE_AND_RUN_TOOL_ID = 'openwop:workflows.compose-and-run';
export const PROPOSE_TOOL_ID = 'openwop:workflows.propose';

function transientCap(): number {
  const raw = Number(process.env.OPENWOP_AGENT_TRANSIENT_WORKFLOWS_MAX);
  return Number.isFinite(raw) && raw > 0 ? raw : 25;
}

/** ADR 0473 — proposal TTL (days). Expired proposals refuse the claim (410). */
function proposalTtlDays(): number {
  const raw = Number(process.env.OPENWOP_WORKFLOW_PROPOSAL_TTL_DAYS);
  return Number.isFinite(raw) && raw > 0 ? raw : 7;
}

const err = (message: string): { content: string; isError: true } =>
  ({ content: JSON.stringify({ error: 'validation_error', message }), isError: true });

/** The read-only definition resolver both lanes probe for id takeover — the
 *  CATALOG, not the registry, because the catalog is what `startWorkflowRun`
 *  dispatches from and it resolves sources the registry can't see (hardcoded
 *  samples, templates, examples, chain-backed ids). A registry-only probe let
 *  an agent mint a draft whose id a catalog source SHADOWS at dispatch — the
 *  reviewer would approve one definition and run another (review F3). */
export interface WorkflowResolver {
  workflowCatalog: { getWorkflow(workflowId: string): Promise<unknown | null> };
}

interface ComposeScope {
  tenantId: string;
  agentProfileId?: string;
  actingUserId?: string;
  conversationId?: string;
}

type PreparedDraft =
  | { ok: true; def: WorkflowDefinition }
  | { ok: false; failure: { content: string; isError: true } };

/** The shared compose pipeline (steps 1–3): schema-validate → the POST /v1/runs
 *  capability refusal → closed-world typeIds → the tenant's disabled-pack
 *  curation → no id takeover. Stores nothing; both lanes call it. */
async function prepareComposedDraft(candidate: unknown, resolver: WorkflowResolver, tenantId: string): Promise<PreparedDraft> {
  if (!candidate || typeof candidate !== 'object' || Array.isArray(candidate)) {
    return { ok: false, failure: err('definition must be a workflow-definition object.') };
  }
  const draft = { ...(candidate as Record<string, unknown>) };
  if (draft.workflowId === undefined) draft.workflowId = `agent-wf-${randomUUID()}`;
  if (typeof draft.workflowId !== 'string' || !WORKFLOW_ID_PATTERN.test(draft.workflowId)) {
    return { ok: false, failure: err('workflowId must match the workflow-id pattern.') };
  }

  // 1. Schema validation FIRST — invalid composes store nothing.
  let def: WorkflowDefinition;
  try {
    def = validateWorkflowDefinition(draft);
  } catch (e) {
    const message = e instanceof OpenwopError ? e.message : String(e);
    return { ok: false, failure: err(`definition failed validation: ${message}`) };
  }

  // 2. The SAME capability refusal POST /v1/runs applies.
  const refusal = capabilityGatedTypeIdRefusal(def.nodes);
  if (refusal) return { ok: false, failure: err(refusal.message) };

  // 2b. CLOSED-WORLD (ADR 0595 — `WFAC-4` = `WFAWF-3`). The step above is a
  //     DOCUMENTED NO-OP today (`routes/runs.ts` `capabilityGatedTypeIdRefusal`
  //     ends `void nodes; return null` — no typeId is currently capability-gated),
  //     so until now this lane had no legality check on node types at all, while
  //     its sibling `feature.workflow-author.nodes.persist` did. The Workflow
  //     Architect holds BOTH doors and picks between them from the user's
  //     PHRASING, so the weaker lane was reachable for the same ask in the same
  //     turn — and an invented typeId would sail past a human reviewer only to
  //     `unknown_typeid` at dispatch, i.e. the reviewer approved something that
  //     could never run.
  //
  //     ONE OWNER, not a third copy: `findUnknownTypeIds` is the same CORE
  //     helper (`host/nodeCatalogBuilder.ts`) `persistAuthoredWorkflow` calls.
  //     This is a second CALL SITE of one rule.
  //
  //     The review gate stays lane-specific and that asymmetry is deliberate:
  //     `persist` produces an INERT artifact a human must choose to run, while
  //     `propose` leads to execution. What must NOT differ is the legality of
  //     what gets written. Reported, not thrown — the agent repairs from it.
  const unknown = findUnknownTypeIds(def);
  if (unknown.length > 0) {
    return {
      ok: false,
      failure: err(
        `definition references Unknown node typeId(s): ${unknown.join(', ')}. `
        + "Every typeId MUST exist in this host's node catalog (closed-world) — call openwop:schema.lookup (family \"node\") and compose only from what it lists.",
      ),
    };
  }

  // 2c. TENANT CURATION (ADR 0595 §Correction 4 — ADR 0194 P3 on the model
  //     doors). The check above resolves against the HOST-GLOBAL catalog, so a
  //     node from a pack THIS workspace disabled passes it. Every human-facing
  //     registration lane (REST create, revision restore, from-chain, collab
  //     derive) has called `assertNoDisabledPacks` since ADR 0194 P3 / ADR 0481;
  //     the two MODEL doors did not, so curation was enforced where a person
  //     writes and skipped where a model writes. Same choke helper, reported
  //     rather than thrown — like 2b, the agent repairs from the message, and
  //     the message already names the fix ("re-enable them in the Marketplace").
  try {
    await assertNoDisabledPacks(def, tenantId);
  } catch (e) {
    return { ok: false, failure: err(e instanceof OpenwopError ? e.message : String(e)) };
  }

  // 3. No id takeover: any id the CATALOG resolves (registry, samples,
  //    templates, examples, chain-backed) is refused outright — dispatch
  //    resolves the catalog, so a catalog-shadowed id would run something the
  //    reviewer never saw.
  if (await resolver.workflowCatalog.getWorkflow(def.workflowId)) {
    return { ok: false, failure: err(`workflowId '${def.workflowId}' already exists — compose with a fresh id.`) };
  }
  return { ok: true, def };
}

/** Step 4 — the per-tenant live-transient abuse bound (ADR 0369 OQ4).
 *
 *  EXPORTED (ADR 0595 §4) so the workflow-author's `persist` lane enforces the
 *  SAME bound rather than growing a second one. Both lanes mint transient drafts
 *  owned by the tenant, so they must share one budget and one definition of
 *  "live" — a per-lane cap would let an agent double the ceiling by alternating
 *  doors, which is the very lane-shopping this ADR closes. `transientCap()` (the
 *  env-configured number) stays private: callers ask the question, they do not
 *  re-derive the answer. */
export async function transientCapReached(tenantId: string): Promise<boolean> {
  const owned = await listOwned(tenantId);
  return owned.filter((o) => o.transient && !o.archivedAt).length >= transientCap();
}

/** The bound's number, for a caller that must put it in a refusal message. */
export const transientCapValue = (): number => transientCap();

/**
 * The ONE refusal message for that bound (ADR 0595 §Correction 7).
 *
 * Two defects it fixes, both in the author lane's hand-written copy:
 *
 *  1. **It named the wrong population.** `transientCapReached` counts EVERY
 *     ownership row with `transient && !archivedAt` — deliberately, so
 *     alternating doors cannot double the ceiling — which includes agent
 *     `propose`/`compose-and-run` drafts and recorded walkthrough tour drafts
 *     (`walkthroughAuthorTool`). The message said "unsaved AI-authored drafts",
 *     so a user whose budget is full of tours and proposals is told to go and
 *     find AI-authored workflows, of which there may be none. The count is
 *     right and stays one budget; the SENTENCE was wrong.
 *  2. **It led with a remedy that can 409.** "Save (promote)" requires a
 *     completed non-debug run plus green `requiredForPromote` evals, so for the
 *     un-run drafts that are actually consuming the budget it fails. Archiving
 *     always works. A refusal must lead with the action that works.
 *
 * Kept beside the counter so the message and the population it describes cannot
 * drift apart again — the drift was possible only because they lived apart.
 */
export const transientCapMessage = (): string =>
  `You already have ${transientCap()} unsaved AI-generated drafts (AI-authored workflows, agent proposals, and `
  + 'recorded tours all draw on this one budget). Archive one you no longer need to free a slot — or promote a '
  + 'draft that has already completed a successful run.';

/** Step 5 — register the draft transient + record tenant ownership. */
async function registerTransientDraft(def: WorkflowDefinition, scope: ComposeScope): Promise<string> {
  const generatedBy = `agent:${scope.agentProfileId ?? 'unattributed'}`;
  // ADR 0595 §Correction 2 — `withHostLifecycle`, NOT `withLifecycle`. The
  // definition body on this lane comes from a MODEL, and `withLifecycle` seeds
  // from `lifecycleOf(def)` and patches only the two keys named here — so a
  // model-supplied `archivedAt` SURVIVED, minting a born-archived draft that is
  // catalog-hidden and GC-eligible from birth while the tool reported
  // `pending_approval`, with the ownership row (written `transient:true`, no
  // `archivedAt`) disagreeing with the definition. `promote` later keeps that
  // `archivedAt`, so the workflow vanishes the instant the user saves it.
  // `withHostLifecycle` DISCARDS the candidate's block outright: the host, not
  // the model, decides visibility — the same ruling ADR 0595 §5 made for the
  // author lane, now on both doors of it.
  const stamped = withHostLifecycle(def, { transient: true, generatedBy });
  // Grade-data D5 — AWAIT the durable def write: ownership + the approval hold
  // persist durably below, and a lost def write would strand them over a draft
  // other instances can't resolve.
  await registerWorkflowDurable(stamped);
  // ADR 0474 — the agent's draft is the first revision (attributed to the agent).
  await recordRevision(scope.tenantId, stamped, { createdBy: generatedBy });
  const name = typeof stamped.metadata?.name === 'string' ? stamped.metadata.name : undefined;
  await recordOwnership(scope.tenantId, def.workflowId, {
    ...(name !== undefined ? { name } : {}),
    nodeCount: def.nodes.length,
    transient: true,
  });
  return generatedBy;
}

export function registerWorkflowComposeTool(deps: StartRunDeps): void {
  registerFeatureAgentTool({
    // TRUSTED: returns host-minted ids and counts ({valid, workflowId, nodeCount}, runId)
    // over the model's OWN composed definition — it reads back no stored text.
    contentTrust: 'trusted',
    def: {
      name: COMPOSE_AND_RUN_TOOL_ID,
      description:
        'Compose a NEW workflow definition (JSON, workflow-definition schema), register it as a transient '
        + 'draft, and run it IMMEDIATELY — no human reviews the composition first (run-level approval gates '
        + 'still apply). This is the AUTONOMOUS lane for headless/scheduled work; when a person is in the '
        + 'conversation, prefer openwop:workflows.propose so they can review before anything runs. The draft '
        + 'stays out of the workflow catalog; only the USER can promote it to a saved workflow (after a '
        + 'successful run). Prefer an existing workflow or a parameterized template when one fits — compose '
        + 'only when the task needs a structure that does not exist yet. Set dryRun=true to validate the '
        + 'definition without registering or running. '
        // XCH-CMP-2 (LLM-EXCHANGE round 4): ground the composer — the schemas
        // are discoverable at runtime, never guessed.
        + 'To discover node types and their config schemas, call the openwop:schema.lookup tool '
        + '(family "node") BEFORE composing — do not invent typeIds. Definition envelope: '
        + '{ workflowId?, metadata?, nodes: [{ nodeId, typeId, config }], edges: [{ edgeId, sourceNodeId, targetNodeId }] }.',
      inputSchema: {
        type: 'object',
        properties: {
          definition: {
            type: 'object',
            description: 'The candidate workflow definition (workflow-definition.schema.json shape: nodes[], edges?, variables?, metadata?). workflowId is optional — one is generated when absent.',
          },
          inputs: { type: 'object', description: 'Run inputs for the composed workflow (optional).' },
          dryRun: { type: 'boolean', description: 'Validate only — nothing is registered and no run starts.' },
        },
        required: ['definition'],
        additionalProperties: false,
      },
    },
    async run(input, scope) {
      const prepared = await prepareComposedDraft(input.definition, deps.hostSuite, scope.tenantId);
      if (!prepared.ok) return prepared.failure;
      const def = prepared.def;

      if (input.dryRun === true) {
        return { content: JSON.stringify({ valid: true, workflowId: def.workflowId, nodeCount: def.nodes.length }) };
      }

      // 4. Abuse bound: live agent-generated transients per tenant.
      if (await transientCapReached(scope.tenantId)) {
        return err(transientCapMessage());
      }

      // 5. Register transient + record ownership (the tenant owns its agent's work).
      const generatedBy = await registerTransientDraft(def, scope);

      // 6. An ORDINARY run via the shared recipe — every run-level gate applies.
      const runId = await startWorkflowRun(deps, {
        tenantId: scope.tenantId,
        workflowId: def.workflowId,
        inputs: (input.inputs && typeof input.inputs === 'object' ? input.inputs as Record<string, unknown> : {}),
        metadata: {
          composedBy: generatedBy,
          ...(scope.actingUserId ? { actingUserId: scope.actingUserId } : {}),
          ...(scope.conversationId ? { chatSessionId: scope.conversationId } : {}),
        },
      });
      if (!runId) return err('the composed workflow registered but its run could not start.');
      log.info('agent composed and ran a transient workflow', { tenantId: scope.tenantId, workflowId: def.workflowId, runId, generatedBy });
      return {
        content: JSON.stringify({
          workflowId: def.workflowId,
          runId,
          lifecycle: 'transient',
          note: 'The draft is catalog-hidden. Promotion to a saved workflow is a user action (requires a successful run).',
        }),
      };
    },
  });
}

/** ADR 0473 (review F8) — bound on the agent-supplied frozen run inputs. */
const RUN_INPUTS_MAX_BYTES = 16_384;

/**
 * ADR 0473 — the propose lane. Deliberately takes only a READ resolver, never
 * `StartRunDeps`: proposing registers the transient draft + creates the
 * `composed-workflow` hold and STOPS. Execution happens only in the decide
 * handler below, after a human claims (and after the post-CAS hash re-verify).
 */
export function registerWorkflowProposeTool(resolver: WorkflowResolver): void {
  registerFeatureAgentTool({
    // TRUSTED: returns host-minted proposal/run ids + a validation verdict — no stored text.
    contentTrust: 'trusted',
    def: {
      name: PROPOSE_TOOL_ID,
      description:
        'PROPOSE a NEW workflow (JSON, workflow-definition schema) for the user to review and approve — '
        + 'nothing runs until they approve. The draft is registered catalog-hidden and editable in the '
        + 'builder; the user sees a review card (in this conversation and the reviews inbox) with '
        + 'Approve & run / open-in-builder / Reject. NEVER claim the workflow ran or will run — say it '
        + 'awaits the user\'s review; the ONE exception is a result with status "auto_approved" (an '
        + 'operator policy pre-approved read-only proposals from you), which includes the started runId. '
        + 'Prefer an existing workflow or a parameterized template when one '
        + 'fits — propose only when the task needs a structure that does not exist yet. Set dryRun=true '
        + 'to validate without registering or proposing. '
        + 'To discover node types and their config schemas, call the openwop:schema.lookup tool '
        + '(family "node") BEFORE composing — do not invent typeIds. Definition envelope: '
        + '{ workflowId?, metadata?, nodes: [{ nodeId, typeId, config }], edges: [{ edgeId, sourceNodeId, targetNodeId }] }.',
      inputSchema: {
        type: 'object',
        properties: {
          definition: {
            type: 'object',
            description: 'The candidate workflow definition (workflow-definition.schema.json shape: nodes[], edges?, variables?, metadata?). workflowId is optional — one is generated when absent.',
          },
          inputs: { type: 'object', description: 'Run inputs the approved run will carry (optional; frozen into the proposal).' },
          summary: { type: 'string', description: 'One sentence for the reviewer: what this workflow does and why you composed it.' },
          reasoning: { type: 'string', description: 'OPTIONAL: your fuller reasoning for the reviewer — why these steps, why this order, what you considered. Shown on the review card attributed to you.' },
          dryRun: { type: 'boolean', description: 'Validate only — nothing is registered and no proposal is created.' },
        },
        required: ['definition'],
        additionalProperties: false,
      },
    },
    async run(input, scope) {
      const prepared = await prepareComposedDraft(input.definition, resolver, scope.tenantId);
      if (!prepared.ok) return prepared.failure;
      const def = prepared.def;

      const runInputs = input.inputs && typeof input.inputs === 'object'
        ? input.inputs as Record<string, unknown>
        : undefined;
      // Review F8 — the frozen inputs are part of what the reviewer approves;
      // bound the agent-supplied blob so the card (and the row) stay renderable.
      if (runInputs && JSON.stringify(runInputs).length > RUN_INPUTS_MAX_BYTES) {
        return err(`inputs too large (${RUN_INPUTS_MAX_BYTES} bytes max) — pass large data through workflow variables or referenced resources.`);
      }

      if (input.dryRun === true) {
        return { content: JSON.stringify({ valid: true, workflowId: def.workflowId, nodeCount: def.nodes.length }) };
      }

      if (await transientCapReached(scope.tenantId)) {
        return err(transientCapMessage());
      }

      const generatedBy = await registerTransientDraft(def, scope);

      // Pin the reviewed definition + freeze the run inputs into the hold.
      const registered = await getRegisteredWorkflowAsync(def.workflowId);
      const pinned = registered ?? def;
      const name = typeof pinned.metadata?.name === 'string' ? pinned.metadata.name : def.workflowId;
      const summary = typeof input.summary === 'string' && input.summary.trim().length > 0
        ? input.summary.trim()
        : `Run the composed workflow "${name}" (${def.nodes.length} nodes).`;
      // ADR 0478 §3 — the agent's stated reasoning (sanitized + capped; a
      // CLAIM the card attributes, never trusted as fact).
      const reasoning = typeof input.reasoning === 'string' && input.reasoning.trim().length > 0
        ? (sanitizeFreeTextDeep(input.reasoning.trim().slice(0, 2000)) as string)
        : undefined;
      const approval = await createComposedWorkflowApproval({
        tenantId: scope.tenantId,
        workflowId: def.workflowId,
        proposal: summary,
        ...(reasoning ? { reasoning } : {}),
        ...(scope.conversationId ? { conversationId: scope.conversationId } : {}),
        composedWorkflow: {
          definitionHash: definitionHashOf(pinned),
          ...(scope.agentProfileId ? { agentProfileId: scope.agentProfileId } : {}),
          // Grade-data H1 — the acting user is the erasure subject for the
          // proposal/reasoning prose composed from their conversation.
          ...(scope.actingUserId ? { proposedByUserId: scope.actingUserId } : {}),
          nodeCount: def.nodes.length,
          edgeCount: def.edges?.length ?? 0,
          expiresAt: new Date(Date.now() + proposalTtlDays() * 24 * 60 * 60 * 1000).toISOString(),
          ...(runInputs ? { runInputs } : {}),
          // ADR 0476 §3 — approve-what-you-see includes what it roughly
          // costs: the static composition floor, computed at PROPOSE time
          // from the same pinned definition the hash covers.
          ...((): Record<string, unknown> => {
            const floor = staticCostFloor(pinned);
            return floor ? { estimatedFloorUsd: floor.floorUsd, estimatedAiNodes: floor.aiNodes } : {};
          })(),
        },
      });
      log.info('agent proposed a composed workflow', {
        tenantId: scope.tenantId, workflowId: def.workflowId, approvalId: approval.approvalId, generatedBy,
      });
      // ADR 0473 Phase 5 — the operator-opt-in policy gate: read-only-class
      // proposals from a policy-named agent auto-approve through the SAME
      // decision core (audited, attributed to the policy). The tool result is
      // honest either way — the model must never guess whether it ran.
      const registeredDef = await getRegisteredWorkflowAsync(def.workflowId);
      const autoRunId = registeredDef
        ? await tryAutoApproveProposal(scope.tenantId, scope.agentProfileId, approval.approvalId, registeredDef)
        : null;
      if (autoRunId) {
        return {
          content: JSON.stringify({
            workflowId: def.workflowId,
            approvalId: approval.approvalId,
            status: 'auto_approved',
            runId: autoRunId,
            builderUrl: `/builder/${def.workflowId}`,
            note: 'An operator policy auto-approved this read-only proposal and the run started; the decision is recorded on the review card.',
          }),
        };
      }
      return {
        content: JSON.stringify({
          workflowId: def.workflowId,
          approvalId: approval.approvalId,
          status: 'pending_approval',
          builderUrl: `/builder/${def.workflowId}`,
          note: 'Nothing ran. The user must review and approve the proposal (review card in this conversation and the reviews inbox); they may edit the draft in the builder first.',
        }),
      };
    },
  });
}

/** Archive a proposal's draft — the ADR 0369 disposal semantic (never
 *  hard-delete; replay/fork re-resolve by id). Best-effort: a vanished or
 *  already-archived def is left alone. Shared by reject + the expiry sweep. */
async function archiveProposalDraft(tenantId: string, workflowId: string): Promise<void> {
  const def = await getRegisteredWorkflowAsync(workflowId);
  if (!def || lifecycleOf(def).archivedAt) return;
  // ADR 0481 (code-review H3) — a live collab room owns the head: defer the
  // archive (best-effort semantics already; the expiry sweep retries later).
  const { workflowRoomLive } = await import('./collab/workflowCollabResource.js');
  if (await workflowRoomLive(workflowId)) {
    log.info('proposal-draft archive deferred — live collab session', { workflowId });
    return;
  }
  const archived = withLifecycle(def, { archivedAt: new Date().toISOString() });
  registerWorkflow(archived);
  const lc = lifecycleOf(archived);
  const name = typeof archived.metadata?.name === 'string' ? archived.metadata.name : undefined;
  await recordOwnership(tenantId, workflowId, {
    ...(name !== undefined ? { name } : {}),
    nodeCount: archived.nodes.length,
    ...(lc.transient !== undefined ? { transient: lc.transient } : {}),
    archivedAt: lc.archivedAt,
  });
}

/** Compensation for a post-CAS refusal: flip the row back to pending, tell the
 *  live review surfaces (the throw path skips `announceReview`), and leave a
 *  compensating audit entry beside the CAS's `approved` chain entry so the
 *  ledger never ends on a decision that did not execute (review F10). */
async function reopenAndSignal(deps: StartRunDeps, tenantId: string, approvalId: string, workflowId: string, why: string, decidedBy?: string): Promise<void> {
  await reopenApproval(approvalId);
  emitReviewUpdatedSignal({ tenantId, reviewId: `approval:${approvalId}`, status: 'pending', approvalId });
  void deps.storage.appendAudit({
    timestamp: new Date().toISOString(),
    principalId: decidedBy ?? 'unknown',
    action: 'workflows.proposal.reopened',
    resource: `workflow:${workflowId}`,
    outcome: 'success',
    payload: { approvalId, tenantId, why },
  }).catch(() => {});
}

/**
 * ADR 0473 — register the `composed-workflow` decide handler. Approve: CAS
 * first (`changed` = the at-most-once lock), then the DEFINITIVE hash re-verify
 * (a builder edit racing the claim must reopen, never run), then the ONE
 * `startWorkflowRun` recipe — which re-verifies the SAME hash against the
 * definition it actually dispatches (the verify→dispatch window, review F2).
 * Reject: archive the draft. Throws `OpenwopError` for the canonical route
 * envelope (409 `proposal_stale` / 409 `proposal_expired` / 422 vanished).
 */
/** ADR 0473 Phase 5 — the decision deps, kept module-level so the propose
 *  tool's policy gate can route an auto-approval through the SAME decision
 *  core a human claim uses (audit + announce + the hash re-verify pipeline).
 *  Set by `registerComposedWorkflowDecisionHandler`; null ⇒ no auto-approve. */
let decisionDeps: ApprovalDecisionDeps | null = null;

/**
 * ADR 0473 Phase 5 — the operator-opt-in auto-approval gate. Fires only when
 * a super-admin-set policy names (tenant, agent) AND every node's declared
 * role is read-only (`pure`/`read`; undeclared blocks — fail-closed). Resolves
 * through `claimApproval` attributed to the policy, so the audit trail and the
 * approve-what-you-see pipeline are identical to a human decision. Returns the
 * started runId, or null when the proposal stays pending (any failure here
 * fails SAFE to pending — never to an unreviewed run).
 */
async function tryAutoApproveProposal(
  tenantId: string,
  agentProfileId: string | undefined,
  approvalId: string,
  def: WorkflowDefinition,
): Promise<string | null> {
  if (!decisionDeps || !agentProfileId) return null;
  try {
    const policy = await getProposalAutoApprovePolicy(tenantId, agentProfileId);
    if (!policy) return null;
    const roles = nodeRoleMap();
    const allReadOnly = def.nodes.every((n) => AUTO_APPROVABLE_ROLES.has(roles.get(n.typeId) ?? 'unclassified'));
    if (!allReadOnly) return null;
    const result = await claimApproval(decisionDeps, { tenantId, decidedBy: policyDeciderRef(policy) }, approvalId);
    if (result.status !== 'approved' || !result.runId) return null;
    log.info('composed-workflow proposal auto-approved by policy', { tenantId, approvalId, agentProfileId, runId: result.runId });
    return result.runId;
  } catch (err) {
    // Fail SAFE: the hold stays pending for a human; log why the policy didn't fire.
    log.warn('proposal auto-approve declined', { tenantId, approvalId, error: err instanceof Error ? err.message : String(err) });
    return null;
  }
}

export function registerComposedWorkflowDecisionHandler(deps: ApprovalDecisionDeps): void {
  decisionDeps = deps;
  registerComposedWorkflowApprovalHandler(async (tenantId, approvalId, outcome, opts) => {
    const approval = await getApproval(approvalId);
    if (!approval || approval.tenantId !== tenantId || approval.kind !== 'composed-workflow') return null;
    if (approval.status !== 'pending') return { approval, changed: false };
    const meta = approval.composedWorkflow;

    if (outcome === 'rejected') {
      const lock = await resolveApproval(approvalId, {
        status: 'rejected',
        ...(opts.decidedByUserId ? { decidedBy: opts.decidedByUserId } : {}),
        ...(opts.note !== undefined ? { note: opts.note } : {}),
      });
      if (!lock) return null;
      if (!lock.changed) return lock;
      await archiveProposalDraft(tenantId, approval.workflowId);
      log.info('composed-workflow proposal rejected', { tenantId, approvalId, workflowId: approval.workflowId });
      return lock;
    }

    // approve —
    // Review F4 — approving EXECUTES an agent-authored definition; the decision
    // must be attributable to a real subject (fail-closed; the sweep's expiry
    // rejects are the only unattributed resolutions).
    if (!opts.decidedByUserId) {
      throw new OpenwopError('forbidden', 'An attributed decider is required to approve a composed workflow.', 403, { approvalId });
    }
    // Expiry: refuse BEFORE any state change (the projection shows it expired).
    // (`conflict` + reason, not a new error code — `OpenwopErrorCode` is a
    // closed wire-adjacent union; a host-local case doesn't extend it.)
    if (meta?.expiresAt && Date.parse(meta.expiresAt) < Date.now()) {
      throw new OpenwopError('conflict', 'Proposal expired — ask the agent to propose again.', 409, { approvalId, reason: 'proposal_expired', expiresAt: meta.expiresAt });
    }
    // Pre-resolve so a vanished draft fails cleanly without flipping the row.
    if (!(await getRegisteredWorkflowAsync(approval.workflowId))) {
      throw new OpenwopError('workflow_not_found', 'Proposed draft no longer resolves.', 422, { workflowId: approval.workflowId });
    }
    // CAS FIRST — only the winning claim proceeds past here.
    const lock = await resolveApproval(approvalId, {
      status: 'approved',
      decidedBy: opts.decidedByUserId,
      ...(opts.note !== undefined ? { note: opts.note } : {}),
    });
    if (!lock) return null;
    if (!lock.changed) return lock;

    // The DEFINITIVE integrity check runs AFTER the lock: a builder edit in the
    // pre-check→lock window must never run unreviewed. Approve-what-you-see
    // (review F1): when the decide carries the hash the reviewer's card
    // DISPLAYED, that is the authority — an edited draft is approvable exactly
    // when the reviewer saw the edited version. Without a client hash the
    // propose-time pin is the only reviewed form.
    const def = await getRegisteredWorkflowAsync(approval.workflowId);
    const liveHash = def ? definitionHashOf(def) : null;
    const reviewedHash = opts.expectedDefinitionHash ?? meta?.definitionHash;
    if (!def || liveHash === null || reviewedHash === undefined || liveHash !== reviewedHash) {
      await reopenAndSignal(deps, tenantId, approvalId, approval.workflowId, 'proposal_stale', opts.decidedByUserId);
      throw new OpenwopError('conflict', 'The draft changed since it was reviewed — re-review the proposal and approve again.', 409, { approvalId, reason: 'proposal_stale' });
    }

    // Dispatch — with the verified hash pinned through to the LAST read
    // (`startWorkflowRun` re-verifies against the definition it resolves, so a
    // racing edit or a catalog-shadowed id refuses instead of running). Any
    // failure past the CAS compensates: never claim "approved" when nothing ran.
    let runId: string | null = null;
    try {
      runId = await startWorkflowRun(deps, {
        tenantId,
        workflowId: approval.workflowId,
        // Review F2 (P1b) — approve-what-you-see means run EXACTLY the content
        // the reviewer's hash covers: the HEAD. Published substitution would
        // hash-mismatch into an unresolvable 409 loop for a promoted draft.
        launch: 'draft',
        expectedDefinitionHash: liveHash,
        ...(meta?.runInputs ? { inputs: meta.runInputs } : {}),
        metadata: {
          approval: {
            approvalId,
            source: 'composed-workflow',
            ...(meta?.agentProfileId ? { agentProfileId: meta.agentProfileId } : {}),
            decidedByUserId: opts.decidedByUserId,
          },
        },
      });
      if (runId) await attachComposedDecision(approvalId, { runId, approvedDefinitionHash: liveHash });
    } catch (dispatchErr) {
      await reopenAndSignal(deps, tenantId, approvalId, approval.workflowId, 'dispatch_failed', opts.decidedByUserId);
      throw dispatchErr;
    }
    if (!runId) {
      await reopenAndSignal(deps, tenantId, approvalId, approval.workflowId, 'dispatch_refused', opts.decidedByUserId);
      if (!(await getRegisteredWorkflowAsync(approval.workflowId))) {
        throw new OpenwopError('workflow_not_found', 'Proposed draft no longer resolves.', 422, { workflowId: approval.workflowId });
      }
      throw new OpenwopError('conflict', 'The definition changed while dispatching — re-review the proposal and approve again.', 409, { approvalId, reason: 'proposal_stale' });
    }
    const final = await getApproval(approvalId);
    log.info('composed-workflow proposal approved and dispatched', { tenantId, approvalId, workflowId: approval.workflowId, runId });
    return { approval: final ?? lock.approval, changed: true };
  });
}

/**
 * ADR 0473 (review F5) — the retention-tick proposal sweep: a PENDING proposal
 * past `expiresAt` resolves to rejected (note `expired`) and its draft
 * archives, so ignored proposals stop pinning the transient cap and the card
 * flips to a terminal state. Called by the retention daemon after the run
 * sweep; unattributed by design (a policy resolution, not a human decision).
 */
export async function sweepExpiredWorkflowProposals(): Promise<{ swept: number; scanned: number; reconciled: number }> {
  const pending = await listPendingApprovalsByKind('composed-workflow');
  let swept = 0;
  const heldTenants = new Map<string, boolean>();
  const isHeld = async (tenantId: string): Promise<boolean> => {
    if (!heldTenants.has(tenantId)) heldTenants.set(tenantId, (await getRetentionHold(tenantId)) !== null);
    return heldTenants.get(tenantId) === true;
  };
  for (const a of pending) {
    const exp = a.composedWorkflow?.expiresAt;
    if (!exp || Date.parse(exp) >= Date.now()) continue;
    // Grade-data D4 — a legal hold freezes the tenant's review state: no
    // policy resolution, no archive (which would make the draft GC-eligible).
    if (await isHeld(a.tenantId)) continue;
    const lock = await resolveApproval(a.approvalId, { status: 'rejected', note: 'expired' });
    if (!lock || !lock.changed) continue; // a concurrent decision won — leave it
    await archiveProposalDraft(a.tenantId, a.workflowId);
    emitReviewUpdatedSignal({ tenantId: a.tenantId, reviewId: `approval:${a.approvalId}`, status: 'rejected', approvalId: a.approvalId });
    swept += 1;
  }
  // Grade-data D3 — crash-window reconciliation: a reject/expiry that resolved
  // the row but died before archiving leaves a live draft pinning the transient
  // cap. `archiveProposalDraft` is idempotent (no-ops on archived/vanished), so
  // sweeping resolved-rejected rows converts that window to delayed-not-lost.
  let reconciled = 0;
  for (const a of await listApprovalsByKindAndStatus('composed-workflow', 'rejected')) {
    if (await isHeld(a.tenantId)) continue;
    const def = await getRegisteredWorkflowAsync(a.workflowId);
    if (!def || lifecycleOf(def).archivedAt || !lifecycleOf(def).transient) continue;
    await archiveProposalDraft(a.tenantId, a.workflowId);
    reconciled += 1;
  }
  const counters = { swept, scanned: pending.length, reconciled };
  lastSweepState = { at: new Date().toISOString(), ...counters };
  if (swept > 0 || reconciled > 0) log.info('workflow proposal sweep', counters);
  return counters;
}

let lastSweepState: { at: string; swept: number; scanned: number; reconciled: number } | null = null;
/** Grade-code C5 — superadmin observability: "did the proposal sweep run, and
 *  when?" is distinguishable from "nothing expired" (the C1 failure's symptom). */
export function lastProposalSweep(): { at: string; swept: number; scanned: number; reconciled: number } | null {
  return lastSweepState;
}
