/**
 * Backend generator (ADR 0423 / ADR 0348 §6e — DECIDE-2 ratified): emits a
 * TypeScript Hono + Drizzle + Postgres backend from the SAME
 * `models[]`/`operations[]` SSoT that produces `openapi.json` — one closed
 * field map, so the contract and the server can never drift.
 *
 * DETERMINISTIC BY CONSTRUCTION: no timestamps, no randomness, dep versions
 * pinned in `PINNED_DEPS`; same canvas state ⇒ byte-identical files (the 6e
 * migrations+SBOM+fixtures artifact discipline — everything is inert,
 * hashable text). Emitted only when the design declares operations.
 */

import { KIND_METHOD } from './openapiGen.js';

interface FieldIn { name?: unknown; type?: unknown; required?: unknown }
interface ModelIn { id?: unknown; name?: unknown; fields?: FieldIn[] }
interface OpIn {
  id?: unknown; name?: unknown; kind?: unknown; purpose?: unknown; modelId?: unknown;
  input?: FieldIn[];
  output?: { type?: unknown; fields?: FieldIn[] };
}
export interface BackendFile { path: string; content: string }

const MAX_MODELS = 40;
const MAX_FIELDS = 40;
const MAX_OPS = 50;

/** Pinned exact versions — the determinism + SBOM source of truth. Bump
 *  deliberately (the emit hash changes with it). */
const PINNED_DEPS: ReadonlyArray<readonly [name: string, version: string]> = [
  ['hono', '4.6.14'],
  ['@hono/node-server', '1.13.7'],
  ['drizzle-orm', '0.38.3'],
  ['postgres', '3.4.5'],
];

/** The closed field map — the Drizzle/SQL twin of openapiGen's FIELD_JSON. */
const FIELD_DRIZZLE: Record<string, { col: (name: string) => string; sql: string }> = {
  string: { col: (n) => `text('${n}')`, sql: 'text' },
  number: { col: (n) => `doublePrecision('${n}')`, sql: 'double precision' },
  boolean: { col: (n) => `boolean('${n}')`, sql: 'boolean' },
  date: { col: (n) => `timestamp('${n}', { withTimezone: true, mode: 'string' })`, sql: 'timestamptz' },
  reference: { col: (n) => `text('${n}')`, sql: 'text' },
  object: { col: (n) => `jsonb('${n}')`, sql: 'jsonb' },
  list: { col: (n) => `jsonb('${n}')`, sql: 'jsonb' },
};

const ident = (raw: unknown): string | null => {
  const s = String(raw ?? '');
  return /^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(s) ? s : null;
};

function cleanModels(state: Record<string, unknown>): Array<{ id: string; fields: Array<{ name: string; type: string; required: boolean }> }> {
  const models = (Array.isArray(state.models) ? state.models : []) as ModelIn[];
  const out: Array<{ id: string; fields: Array<{ name: string; type: string; required: boolean }> }> = [];
  for (const m of models.slice(0, MAX_MODELS)) {
    const id = ident(m?.id);
    if (!id) continue;
    const fields: Array<{ name: string; type: string; required: boolean }> = [];
    for (const f of (m.fields ?? []).slice(0, MAX_FIELDS)) {
      const name = ident(f?.name);
      if (!name || name === 'id') continue;
      const type = FIELD_DRIZZLE[String(f?.type)] ? String(f?.type) : 'string';
      fields.push({ name, type, required: f?.required === true });
    }
    out.push({ id, fields });
  }
  return out;
}

function cleanOps(state: Record<string, unknown>): Array<{ id: string; kind: string; modelId: string | null; name: string; input: Array<{ name: string; type: string; required: boolean }>; outputType: string; outputFields: Array<{ name: string; type: string }> }> {
  const ops = (Array.isArray(state.operations) ? state.operations : []) as OpIn[];
  const out = [];
  for (const op of ops.slice(0, MAX_OPS)) {
    const id = ident(op?.id);
    if (!id) continue;
    const input = [];
    for (const f of (op.input ?? []).slice(0, MAX_FIELDS)) {
      const name = ident(f?.name);
      if (name) input.push({ name, type: FIELD_DRIZZLE[String(f?.type)] ? String(f?.type) : 'string', required: f?.required === true });
    }
    out.push({
      id,
      kind: KIND_METHOD[String(op?.kind)] ? String(op?.kind) : 'action',
      modelId: ident(op?.modelId),
      name: typeof op?.name === 'string' ? op.name : id,
      input,
      outputType: String(op?.output?.type ?? ''),
      outputFields: (op?.output?.fields ?? []).slice(0, MAX_FIELDS).flatMap((f) => {
        const n = ident(f?.name);
        return n ? [{ name: n, type: String(f?.type ?? 'string') }] : [];
      }),
    });
  }
  return out;
}

// ── emitters ─────────────────────────────────────────────────────────────────

function emitSchema(models: ReturnType<typeof cleanModels>): string {
  const lines = [
    '// GENERATED by the OpenWOP app-builder backend generator (ADR 0423).',
    '// Source of truth: the canvas models[] — regenerate rather than hand-edit.',
    "import { pgTable, text, boolean, doublePrecision, timestamp, jsonb } from 'drizzle-orm/pg-core';",
    '',
  ];
  for (const m of models) {
    lines.push(`export const ${m.id} = pgTable('${m.id}', {`);
    lines.push(`  id: text('id').primaryKey(),`);
    for (const f of m.fields) {
      const col = FIELD_DRIZZLE[f.type]!.col(f.name);
      lines.push(`  ${f.name}: ${col}${f.required ? '.notNull()' : ''},`);
    }
    lines.push('});', '');
  }
  return lines.join('\n');
}

function emitMigration(models: ReturnType<typeof cleanModels>): string {
  const stmts = models.map((m) => {
    const cols = [
      '  "id" text PRIMARY KEY',
      ...m.fields.map((f) => `  "${f.name}" ${FIELD_DRIZZLE[f.type]!.sql}${f.required ? ' NOT NULL' : ''}`),
    ];
    return `CREATE TABLE IF NOT EXISTS "${m.id}" (\n${cols.join(',\n')}\n);`;
  });
  return `-- GENERATED initial migration (ADR 0423). Inert, hashable, replayable.\n${stmts.join('\n\n')}\n`;
}

function emitRoutes(ops: ReturnType<typeof cleanOps>, models: ReturnType<typeof cleanModels>): string {
  const modelIds = new Set(models.map((m) => m.id));
  const lines = [
    '// GENERATED routes (ADR 0423) — one handler per canvas operation, method/path',
    '// identical to the exported openapi.json (the shared kind map).',
    "import { Hono } from 'hono';",
    "import { eq } from 'drizzle-orm';",
    "import { db } from './db/client.js';",
    "import * as schema from './db/schema.js';",
    '',
    'export const app = new Hono();',
    '',
  ];
  for (const op of ops) {
    const method = KIND_METHOD[op.kind] ?? 'post';
    const path = `/operations/${op.id}`;
    const table = op.modelId && modelIds.has(op.modelId) ? `schema.${op.modelId}` : null;
    lines.push(`// ${op.name} (kind: ${op.kind})`);
    if (!table || op.kind === 'action') {
      lines.push(`app.${method}('${path}', (c) => c.json({ error: 'not_implemented', operation: '${op.id}' }, 501));`, '');
      continue;
    }
    if (op.kind === 'list') {
      lines.push(`app.get('${path}', async (c) => c.json(await db.select().from(${table})));`, '');
    } else if (op.kind === 'get') {
      lines.push(`app.get('${path}', async (c) => {`);
      lines.push(`  const id = c.req.query('id');`);
      lines.push(`  if (!id) return c.json({ error: 'id required' }, 422);`);
      lines.push(`  const rows = await db.select().from(${table}).where(eq(${table}.id, id));`);
      lines.push(`  return rows[0] ? c.json(rows[0]) : c.json({ error: 'not_found' }, 404);`);
      lines.push('});', '');
    } else if (op.kind === 'create') {
      lines.push(`app.post('${path}', async (c) => {`);
      lines.push(`  const body = await c.req.json();`);
      lines.push(`  const row = { id: crypto.randomUUID(), ...body };`);
      lines.push(`  await db.insert(${table}).values(row);`);
      lines.push(`  return c.json(row, 201);`);
      lines.push('});', '');
    } else if (op.kind === 'update') {
      lines.push(`app.patch('${path}', async (c) => {`);
      lines.push(`  const body = await c.req.json();`);
      lines.push(`  if (!body.id) return c.json({ error: 'id required' }, 422);`);
      lines.push(`  const { id, ...patch } = body;`);
      lines.push(`  await db.update(${table}).set(patch).where(eq(${table}.id, id));`);
      lines.push(`  return c.json({ ok: true });`);
      lines.push('});', '');
    } else if (op.kind === 'delete') {
      lines.push(`app.delete('${path}', async (c) => {`);
      lines.push(`  const id = c.req.query('id');`);
      lines.push(`  if (!id) return c.json({ error: 'id required' }, 422);`);
      lines.push(`  await db.delete(${table}).where(eq(${table}.id, id));`);
      lines.push(`  return c.json({ ok: true });`);
      lines.push('});', '');
    }
  }
  return lines.join('\n');
}

function sampleFor(type: string): unknown {
  switch (type) {
    case 'number': return 1;
    case 'boolean': return true;
    case 'date': return '2026-01-01T00:00:00.000Z';
    case 'object': return {};
    case 'list': return [];
    default: return 'sample';
  }
}

function emitFixture(op: ReturnType<typeof cleanOps>[number]): string {
  const request = Object.fromEntries(op.input.map((f) => [f.name, sampleFor(f.type)]));
  const response = op.outputType === 'none' ? null
    : op.outputFields.length ? Object.fromEntries(op.outputFields.map((f) => [f.name, sampleFor(f.type)]))
    : { ok: true };
  return JSON.stringify({ operationId: op.id, request, response }, null, 2) + '\n';
}

function emitSbom(): string {
  const components = PINNED_DEPS.map(([name, version]) => ({
    type: 'library', 'bom-ref': `pkg:npm/${name}@${version}`, name, version, purl: `pkg:npm/${name}@${version}`,
  }));
  // CycloneDX 1.5, minimal + deterministic (no serialNumber/timestamp — those
  // would break the byte-identical emit gate; consumers may stamp their own).
  return JSON.stringify({ bomFormat: 'CycloneDX', specVersion: '1.5', version: 1, components }, null, 2) + '\n';
}

const STATIC_FILES: ReadonlyArray<BackendFile> = [
  {
    path: 'backend/src/db/client.ts',
    content: [
      '// GENERATED (ADR 0423). DATABASE_URL is injected by the deploy environment —',
      '// never hardcode credentials in generated source.',
      "import { drizzle } from 'drizzle-orm/postgres-js';",
      "import postgres from 'postgres';",
      "const url = process.env.DATABASE_URL;",
      "if (!url) throw new Error('DATABASE_URL is required');",
      'export const db = drizzle(postgres(url));',
      '',
    ].join('\n'),
  },
  {
    path: 'backend/src/index.ts',
    content: [
      '// GENERATED server entry (ADR 0423).',
      "import { serve } from '@hono/node-server';",
      "import { app } from './routes.js';",
      "const port = Number(process.env.PORT ?? 8080);",
      'serve({ fetch: app.fetch, port });',
      "console.log(`listening on :${port}`);",
      '',
    ].join('\n'),
  },
  {
    path: 'backend/Dockerfile',
    content: [
      '# GENERATED (ADR 0423) — Cloud Run-ready (the DECIDE-1 lane).',
      'FROM node:22-slim',
      'WORKDIR /app',
      'COPY package.json ./',
      'RUN npm install --omit=dev',
      'COPY src ./src',
      'RUN npx tsc --init >/dev/null 2>&1 || true',
      'ENV PORT=8080',
      'CMD ["npx", "tsx", "src/index.ts"]',
      '',
    ].join('\n'),
  },
];

/** Emit the backend bundle — [] when the design declares no operations (the
 *  openapi.json rule: no dead scaffolding). */
export function generateBackend(state: Record<string, unknown>): BackendFile[] {
  const ops = cleanOps(state);
  if (!ops.length) return [];
  const models = cleanModels(state);
  const files: BackendFile[] = [
    {
      path: 'backend/package.json',
      content: JSON.stringify({
        name: 'generated-backend', private: true, type: 'module',
        scripts: { start: 'tsx src/index.ts' },
        dependencies: Object.fromEntries(PINNED_DEPS),
        devDependencies: { tsx: '4.19.2', typescript: '5.7.2' },
      }, null, 2) + '\n',
    },
    { path: 'backend/src/db/schema.ts', content: emitSchema(models) },
    { path: 'backend/drizzle/0000_init.sql', content: emitMigration(models) },
    { path: 'backend/src/routes.ts', content: emitRoutes(ops, models) },
    ...STATIC_FILES,
    { path: 'backend/sbom.cdx.json', content: emitSbom() },
    ...ops.map((op) => ({ path: `backend/test/fixtures/${op.id}.json`, content: emitFixture(op) })),
  ];
  return files;
}
