/**
 * OpenAPI generation from the app contract (ADR 0348 6d — DA-10). The
 * document's `models[]`/`operations[]` (closed typed field lists, ADR 0343)
 * project into an OpenAPI 3.1 document: component schemas from models,
 * one path per operation (kind-idiomatic method/path), `x-openwop-source`
 * carrying the canvas address (the shared `sourceAddress` grammar family) so
 * generated contract lines trace back to canvas fields. Pure + bounded; only
 * emitted when the design declares operations.
 */

interface ModelIn { id?: unknown; name?: unknown; fields?: { name?: unknown; type?: unknown; required?: unknown }[] }
interface OpIn {
  id?: unknown; name?: unknown; kind?: unknown; purpose?: unknown; modelId?: unknown; auth?: unknown;
  input?: { name?: unknown; type?: unknown; required?: unknown }[];
  output?: { type?: unknown; fields?: { name?: unknown; type?: unknown }[] };
}

const FIELD_JSON: Record<string, object> = {
  string: { type: 'string' },
  number: { type: 'number' },
  boolean: { type: 'boolean' },
  date: { type: 'string', format: 'date-time' },
  reference: { type: 'string', description: 'The id of the referenced record.' },
  object: { type: 'object' },
  list: { type: 'array', items: {} },
};

/** The ONE kind→HTTP-method map — shared with the backend generator (ADR 0423)
 *  so routes and the OpenAPI contract can never drift. */
export const KIND_METHOD: Record<string, string> = { list: 'get', get: 'get', create: 'post', update: 'patch', delete: 'delete', action: 'post' };

function fieldsToSchema(fields: { name?: unknown; type?: unknown; required?: unknown }[] | undefined): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];
  for (const f of (fields ?? []).slice(0, 40)) {
    if (typeof f?.name !== 'string' || !f.name) continue;
    properties[f.name] = FIELD_JSON[String(f.type)] ?? { type: 'string' };
    if (f.required === true) required.push(f.name);
  }
  return { type: 'object', properties, ...(required.length ? { required } : {}), additionalProperties: false };
}

/** null when the design declares no operations — no dead openapi.json. */
export function generateOpenApi(state: Record<string, unknown>): Record<string, unknown> | null {
  const operations = (Array.isArray(state.operations) ? state.operations : []) as OpIn[];
  if (!operations.length) return null;
  const models = (Array.isArray(state.models) ? state.models : []) as ModelIn[];
  const schemas: Record<string, unknown> = {};
  for (const [i, m] of models.entries()) {
    if (typeof m?.id !== 'string' || !m.id) continue;
    schemas[m.id] = { ...fieldsToSchema(m.fields), 'x-openwop-source': `models[${m.id}]`, ...(typeof m.name === 'string' ? { title: m.name } : {}), description: `Generated from canvas model #${i + 1}.` };
  }
  const paths: Record<string, unknown> = {};
  for (const op of operations.slice(0, 50)) {
    if (typeof op?.id !== 'string' || !op.id) continue;
    const kind = String(op.kind ?? 'action');
    const method = KIND_METHOD[kind] ?? 'post';
    const modelRef = typeof op.modelId === 'string' && op.modelId && schemas[op.modelId] ? { $ref: `#/components/schemas/${op.modelId}` } : { type: 'object' as const };
    const outType = String(op.output?.type ?? (kind === 'list' ? 'modelList' : 'object'));
    const responseSchema = outType === 'modelList' ? { type: 'array', items: modelRef }
      : outType === 'model' ? modelRef
      : outType === 'none' ? undefined
      : op.output?.fields?.length ? fieldsToSchema(op.output.fields) : { type: 'object' };
    const path = `/operations/${op.id}`;
    paths[path] = {
      [method]: {
        operationId: op.id,
        summary: typeof op.name === 'string' ? op.name : op.id,
        ...(typeof op.purpose === 'string' && op.purpose ? { description: op.purpose } : {}),
        'x-openwop-source': `operations[${op.id}]`,
        ...(op.auth === 'user' || op.auth === 'role' ? { security: [{ appAuth: [] }] } : {}),
        ...(op.input?.length && method !== 'get'
          ? { requestBody: { required: true, content: { 'application/json': { schema: fieldsToSchema(op.input) } } } }
          : {}),
        ...(op.input?.length && method === 'get'
          ? { parameters: op.input.slice(0, 20).flatMap((f) => (typeof f?.name === 'string' && f.name ? [{ name: f.name, in: 'query', required: f.required === true, schema: FIELD_JSON[String(f.type)] ?? { type: 'string' } }] : [])) }
          : {}),
        responses: {
          '200': responseSchema
            ? { description: 'OK', content: { 'application/json': { schema: responseSchema } } }
            : { description: 'OK' },
        },
      },
    };
  }
  return {
    openapi: '3.1.0',
    info: {
      title: typeof state.name === 'string' ? `${state.name} API` : 'Generated API',
      version: '0.1.0',
      description: 'Generated by OpenWOP App Builder from the design\'s models and operations (a design-time contract, not a running service).',
    },
    paths,
    components: {
      schemas,
      securitySchemes: { appAuth: { type: 'http', scheme: 'bearer' } },
    },
  };
}
