/**
 * Production Intelligence store (ADR 0172) — the org-scoped Vendor Directory +
 * the generated ProductionPlan record. Completes the MyndHyve "Production
 * Intelligence (CS-010)" port that ADR 0005 began (Team Profiles only).
 *
 * BOUNDARIES (the boundaries audit, ADR 0172 § Context):
 *  - The `Vendor` entity is the ONE net-new store here. External-org identity a
 *    vendor may map to lives in CRM (`Company`) — a vendor OPTIONALLY references a
 *    `companyId`; it does not re-model the company.
 *  - Team capability data is NOT owned here — it stays in Profiles (ADR 0005);
 *    the context builder reads `profilesService.listProfiles`.
 *  - The `ProductionPlan` is generated by a workflow run (the
 *    `feature.production.nodes.plan-generate` node) and additionally projected as
 *    a run-output artifact (ADR 0055/0083); this record is the durable
 *    source-of-truth for the plan's lifecycle status.
 *
 * Every record carries tenantId + orgId and every accessor verifies BOTH (CTI-1
 * IDOR guard — the CRM `crmEntitiesService` pattern). A vendor field confers NO
 * authority (RFC 0087 §B, the ADR 0005 invariant): quality/contract/capabilities
 * are descriptive and never widen a scope.
 *
 * @see docs/adr/0172-production-intelligence-vendor-directory.md
 */

import { randomUUID } from 'node:crypto';
import { createLogger } from '../../observability/logger.js';
import { DurableCollection } from '../../host/hostExtPersistence.js';
import { declarePiiFields } from '../../host/dataClassification.js';
import { OpenwopError } from '../../types.js';
import { cleanString, optionalCleanString, cleanTagList } from '../../host/boundedStrings.js';

const log = createLogger('production');

// ── Bounded-string caps + shared helpers (crmEntitiesService parity) ──────────
const MAX = { name: 200, short: 120, notes: 2000, capName: 100, caps: 40, prices: 40, past: 40, tokens: 24, perOrg: 5000 } as const;

function nowIso(): string {
  return new Date().toISOString();
}
const cleanStr = (raw: unknown, max: number, fallback = ''): string => cleanString(raw, max, fallback);
const optStr = (raw: unknown, max: number): string | undefined => optionalCleanString(raw, max);

/** Per-org entity cap (parity with CRM/media). */
function assertCap(count: number, label: string): void {
  if (count >= MAX.perOrg) {
    throw new OpenwopError('validation_error', `This org has the maximum ${MAX.perOrg} ${label}.`, 409, { max: MAX.perOrg });
  }
}

/**
 * Production capability taxonomy. The channel→category map + a skill-name→category
 * inference (profiles carry free-text skill NAMES, no category enum — ADR 0172
 * port-not-clone adaptation) both key off this set. `'other'` is the safe fallback.
 */
export const PRODUCTION_CATEGORIES = [
  'design', 'development', 'writing', 'video', 'photography', 'audio', 'strategy', 'social-media', 'other',
] as const;
export type ProductionCategory = (typeof PRODUCTION_CATEGORIES)[number];

function toCategory(raw: unknown): ProductionCategory {
  const s = typeof raw === 'string' ? raw.trim().toLowerCase() : '';
  return (PRODUCTION_CATEGORIES as readonly string[]).includes(s) ? (s as ProductionCategory) : 'other';
}

function clamp1to5(raw: unknown): number | undefined {
  return typeof raw === 'number' && Number.isFinite(raw) ? Math.max(1, Math.min(5, Math.round(raw))) : undefined;
}
function nonNegNum(raw: unknown): number | undefined {
  return typeof raw === 'number' && Number.isFinite(raw) && raw >= 0 ? raw : undefined;
}

// ── Vendor ────────────────────────────────────────────────────────────────

export const PRICE_UNITS = ['per-hour', 'per-project', 'per-month', 'per-word', 'per-asset'] as const;
export type PriceUnit = (typeof PRICE_UNITS)[number];
export const VENDOR_TYPES = ['contractor', 'agency'] as const;
export type VendorType = (typeof VENDOR_TYPES)[number];
export const CONTRACT_STATUSES = ['active', 'inactive', 'preferred'] as const;
export type ContractStatus = (typeof CONTRACT_STATUSES)[number];

export interface VendorCapability {
  name: string;
  category: ProductionCategory;
  qualityRating?: number; // 1..5
}
export interface PriceRange {
  capability: string;
  min: number;
  max: number;
  unit: PriceUnit;
}
export interface VendorPastProject {
  projectId: string;
  name: string;
  completedAt?: string;
}

export interface Vendor {
  vendorId: string;
  tenantId: string;
  orgId: string;
  type: VendorType;
  name: string;
  /** OPTIONAL reference to a CRM `Company` (ADR 0008) — validated same tenant+org. */
  companyId?: string;
  contactEmail?: string;
  website?: string;
  region?: string;
  capabilities: VendorCapability[];
  priceRanges: PriceRange[];
  pastProjects: VendorPastProject[];
  /** Media-asset references (bytes stay in the media surface, RFC 0055). */
  portfolioAssetTokens: string[];
  contractStatus: ContractStatus;
  notes?: string;
  lastVerifiedAt?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

// PROD2-M6 (R3) — `contactEmail` is an EXTERNAL person's address; `contact_email`
// matches neither PII_EXACT nor PII_COMPOUND, so without this declaration it was
// structurally invisible to the classification tooling. (Excluding vendors from
// ERASURE stays deliberate — the CRM third-party-record precedent — but an
// undeclared PII field is not a posture, it's a blind spot.)
declarePiiFields('production.vendor', ['contactEmail']);


const vendors = new DurableCollection<Vendor>('production:vendor', (v) => v.vendorId, undefined, (v) => v.tenantId);

function cleanCapabilities(raw: unknown): VendorCapability[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .slice(0, MAX.caps)
    .map((c) => {
      const o = (c ?? {}) as Record<string, unknown>;
      const name = optStr(o.name, MAX.capName);
      if (!name) return null;
      const cap: VendorCapability = { name, category: toCategory(o.category) };
      const q = clamp1to5(o.qualityRating);
      if (q !== undefined) cap.qualityRating = q;
      return cap;
    })
    .filter((c): c is VendorCapability => c !== null);
}

function cleanPriceRanges(raw: unknown): PriceRange[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .slice(0, MAX.prices)
    .map((p) => {
      const o = (p ?? {}) as Record<string, unknown>;
      const capability = optStr(o.capability, MAX.capName);
      const min = nonNegNum(o.min);
      const max = nonNegNum(o.max);
      const unit = typeof o.unit === 'string' && (PRICE_UNITS as readonly string[]).includes(o.unit) ? (o.unit as PriceUnit) : undefined;
      if (!capability || min === undefined || max === undefined || !unit) return null;
      // Normalize an inverted range rather than persisting min>max.
      return { capability, min: Math.min(min, max), max: Math.max(min, max), unit };
    })
    .filter((p): p is PriceRange => p !== null);
}

function cleanPastProjects(raw: unknown): VendorPastProject[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .slice(0, MAX.past)
    .map((p) => {
      const o = (p ?? {}) as Record<string, unknown>;
      const projectId = optStr(o.projectId, MAX.short);
      const name = optStr(o.name, MAX.name);
      if (!projectId || !name) return null;
      const proj: VendorPastProject = { projectId, name };
      const completedAt = optStr(o.completedAt, 40);
      if (completedAt) proj.completedAt = completedAt;
      return proj;
    })
    .filter((p): p is VendorPastProject => p !== null);
}

function cleanTokens(raw: unknown): string[] {
  return cleanTagList(raw, { maxTags: MAX.tokens, maxLen: 400 });
}

export async function listVendors(
  tenantId: string,
  orgId: string,
  filter?: { q?: string; type?: VendorType; contractStatus?: ContractStatus },
): Promise<Vendor[]> {
  const needle = filter?.q?.trim().toLowerCase();
  return (await vendors.listForTenantIndexed(tenantId))
    .filter((v) => v.orgId === orgId)
    .filter((v) => (!filter?.type ? true : v.type === filter.type))
    .filter((v) => (!filter?.contractStatus ? true : v.contractStatus === filter.contractStatus))
    .filter((v) => (!needle ? true : v.name.toLowerCase().includes(needle)))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export async function getVendor(tenantId: string, orgId: string, vendorId: string): Promise<Vendor | null> {
  const v = await vendors.get(vendorId);
  return v && v.tenantId === tenantId && v.orgId === orgId ? v : null;
}

export interface VendorInput {
  tenantId: string;
  orgId: string;
  type: unknown;
  name: unknown;
  companyId?: string;
  contactEmail?: unknown;
  website?: unknown;
  region?: unknown;
  capabilities?: unknown;
  priceRanges?: unknown;
  pastProjects?: unknown;
  portfolioAssetTokens?: unknown;
  contractStatus?: unknown;
  notes?: unknown;
  lastVerifiedAt?: unknown;
  createdBy: string;
}

export async function createVendor(input: VendorInput): Promise<Vendor> {
  assertCap((await listVendors(input.tenantId, input.orgId)).length, 'vendors');
  const ts = nowIso();
  const type: VendorType = (VENDOR_TYPES as readonly string[]).includes(String(input.type)) ? (input.type as VendorType) : 'contractor';
  const contractStatus: ContractStatus = (CONTRACT_STATUSES as readonly string[]).includes(String(input.contractStatus))
    ? (input.contractStatus as ContractStatus)
    : 'active';
  const v: Vendor = {
    vendorId: `vnd:${randomUUID()}`,
    tenantId: input.tenantId,
    orgId: input.orgId,
    type,
    name: cleanStr(input.name, MAX.name, 'Untitled vendor'),
    ...(input.companyId ? { companyId: input.companyId } : {}),
    ...(optStr(input.contactEmail, MAX.short) ? { contactEmail: optStr(input.contactEmail, MAX.short) } : {}),
    ...(optStr(input.website, MAX.short) ? { website: optStr(input.website, MAX.short) } : {}),
    ...(optStr(input.region, MAX.short) ? { region: optStr(input.region, MAX.short) } : {}),
    capabilities: cleanCapabilities(input.capabilities),
    priceRanges: cleanPriceRanges(input.priceRanges),
    pastProjects: cleanPastProjects(input.pastProjects),
    portfolioAssetTokens: cleanTokens(input.portfolioAssetTokens),
    contractStatus,
    ...(optStr(input.notes, MAX.notes) ? { notes: optStr(input.notes, MAX.notes) } : {}),
    ...(optStr(input.lastVerifiedAt, 40) ? { lastVerifiedAt: optStr(input.lastVerifiedAt, 40) } : {}),
    createdBy: input.createdBy,
    createdAt: ts,
    updatedAt: ts,
  };
  await vendors.put(v);
  return v;
}

export interface VendorPatch {
  type?: VendorType;
  name?: string;
  companyId?: string | null;
  contactEmail?: string | null;
  website?: string | null;
  region?: string | null;
  capabilities?: unknown;
  priceRanges?: unknown;
  pastProjects?: unknown;
  contractStatus?: ContractStatus;
  notes?: string | null;
  lastVerifiedAt?: string | null;
}

export async function updateVendor(tenantId: string, orgId: string, vendorId: string, patch: VendorPatch): Promise<Vendor | null> {
  const v = await getVendor(tenantId, orgId, vendorId);
  if (!v) return null;
  const next: Vendor = { ...v, updatedAt: nowIso() };
  if (patch.type !== undefined && (VENDOR_TYPES as readonly string[]).includes(patch.type)) next.type = patch.type;
  if (patch.name !== undefined) next.name = cleanStr(patch.name, MAX.name, v.name);
  if (patch.companyId !== undefined) {
    if (patch.companyId === null) delete next.companyId;
    else next.companyId = patch.companyId;
  }
  const optField = (key: 'contactEmail' | 'website' | 'region' | 'notes' | 'lastVerifiedAt', max: number): void => {
    const raw = patch[key];
    if (raw === undefined) return;
    if (raw === null) delete next[key];
    else next[key] = optStr(raw, max);
  };
  optField('contactEmail', MAX.short);
  optField('website', MAX.short);
  optField('region', MAX.short);
  optField('notes', MAX.notes);
  optField('lastVerifiedAt', 40);
  if (patch.capabilities !== undefined) next.capabilities = cleanCapabilities(patch.capabilities);
  if (patch.priceRanges !== undefined) next.priceRanges = cleanPriceRanges(patch.priceRanges);
  if (patch.pastProjects !== undefined) next.pastProjects = cleanPastProjects(patch.pastProjects);
  if (patch.contractStatus !== undefined && (CONTRACT_STATUSES as readonly string[]).includes(patch.contractStatus)) {
    next.contractStatus = patch.contractStatus;
  }
  await vendors.put(next);
  return next;
}

export async function deleteVendor(tenantId: string, orgId: string, vendorId: string): Promise<boolean> {
  const v = await getVendor(tenantId, orgId, vendorId);
  if (!v) return false;
  await vendors.delete(vendorId);
  return true;
}

/** Replace the vendor's portfolio media-asset token set (bounded). Returns the
 *  updated vendor or null. Tokens are references only; bytes stay in Media. */
export async function setVendorPortfolio(tenantId: string, orgId: string, vendorId: string, tokens: unknown): Promise<Vendor | null> {
  const v = await getVendor(tenantId, orgId, vendorId);
  if (!v) return null;
  const next: Vendor = { ...v, portfolioAssetTokens: cleanTokens(tokens), updatedAt: nowIso() };
  await vendors.put(next);
  return next;
}

// ── ProductionPlan ──────────────────────────────────────────────────────────

const EXECUTION_ROUTES = ['internal', 'contractor', 'agency', 'hybrid'] as const;
export type ExecutionRoute = (typeof EXECUTION_ROUTES)[number];
export const PLAN_STATUSES = ['draft', 'approved', 'in_production', 'completed'] as const;
export type PlanStatus = (typeof PLAN_STATUSES)[number];

export interface BudgetEstimate {
  min: number;
  max: number;
  currency: string;
  breakdown?: { item: string; cost: number }[];
}
export interface ProductionRecommendation {
  assetType: string;
  assetDescription: string;
  executionRoute: ExecutionRoute;
  rationale: string;
  budget: BudgetEstimate;
  timelineEstimate: string;
  internalMatch?: { suggestedMembers: { name: string; role: string; fitReason: string }[]; matchingSkills: string[]; gaps: string[] };
  matchingVendors?: { vendorId: string; name: string; type: VendorType; matchReason: string }[];
}
export interface ProductionPlan {
  planId: string;
  tenantId: string;
  orgId: string;
  /** Provenance — OPTIONAL: the plan is decoupled from any one caller (ADR 0172). */
  briefId?: string;
  workflowRunId?: string;
  strategySummary: string;
  recommendations: ProductionRecommendation[];
  totalBudget: BudgetEstimate;
  timeline: { estimatedDeliveryDate?: string; milestones: { date: string; deliverable: string }[] };
  capabilityAssessment: { strengths: string[]; gaps: string[]; overallRecommendation: string; confidence: number };
  status: PlanStatus;
  generatedAt: string;
  updatedAt: string;
  updatedBy?: string;
}

const plans = new DurableCollection<ProductionPlan>('production:plan', (p) => p.planId, undefined, (p) => p.tenantId);

export async function listPlans(tenantId: string, orgId: string): Promise<ProductionPlan[]> {
  return (await plans.listForTenantIndexed(tenantId))
    .filter((p) => p.orgId === orgId)
    .sort((a, b) => b.generatedAt.localeCompare(a.generatedAt));
}

export async function getPlan(tenantId: string, orgId: string, planId: string): Promise<ProductionPlan | null> {
  const p = await plans.get(planId);
  return p && p.tenantId === tenantId && p.orgId === orgId ? p : null;
}

/**
 * Persist a generated plan (called from the `plan-generate` node — role:action, so
 * the node OUTPUT is recorded and replay/fork reads it verbatim; this write is the
 * durable lifecycle record). Idempotent per `planId`: a re-run with the same id
 * (e.g. derived from the workflow run) upserts rather than duplicating.
 */
/**
 * PIC-2 — reject SEMANTICALLY-invalid model output BEFORE it reaches durable state.
 * The field cleaners below still COERCE cosmetic issues (length caps, currency ISO
 * normalisation per PROD2-R2, numeric clamping, array truncation) — those don't
 * change a plan's meaning and the model can't usefully "repair" a 121-char string.
 * But a structural/enum violation that would SILENTLY CHANGE meaning (a non-array
 * `recommendations` coerced to `[]`, an unknown `executionRoute` coerced to
 * 'internal', an unknown vendor `type` coerced to 'contractor') is a typed failure,
 * never success-with-empty (the repo non-negotiable). Keyed on the SSoT enum
 * constants (EXECUTION_ROUTES / VENDOR_TYPES) so the reject boundary can't drift
 * from the coercion sets or the `production.plan` artifact schema. A legitimately
 * sparse-but-well-formed plan (empty recommendations, absent optionals) still
 * persists — this rejects malformed, not minimal.
 */
function assertValidPlanContent(input: { strategySummary: unknown; recommendations?: unknown }): void {
  const errors: string[] = [];
  if (typeof input.strategySummary !== 'string' || input.strategySummary.trim() === '') {
    errors.push('strategySummary is required and must be a non-empty string.');
  }
  const recs = input.recommendations;
  if (recs !== undefined && recs !== null && !Array.isArray(recs)) {
    errors.push('recommendations must be an array.');
  } else if (Array.isArray(recs)) {
    recs.forEach((r, i) => {
      // A non-object entry (a primitive / null / nested array) would otherwise be
      // fabricated into a full placeholder rec by cleanRecommendations — the same
      // succeed-with-placeholder class this gate exists to stop.
      if (r === null || typeof r !== 'object' || Array.isArray(r)) {
        errors.push(`recommendations[${i}] must be an object.`);
        return;
      }
      const o = r as Record<string, unknown>;
      if (o.executionRoute != null && !(EXECUTION_ROUTES as readonly string[]).includes(String(o.executionRoute))) {
        errors.push(`recommendations[${i}].executionRoute '${String(o.executionRoute)}' is not one of: ${EXECUTION_ROUTES.join(', ')}.`);
      }
      // NOTE: matchingVendors are deliberately NOT type-gated here — PIC-1 already
      // DROPS hallucinated vendors (vendorId not in the org directory) at cleaning
      // time, and a directory-backed vendor's `type` label is advisory (coerced),
      // so rejecting the whole plan on it would escalate a droppable vendor into a
      // hard failure (a regression on the case PIC-1 was built to absorb).
    });
  }
  if (errors.length) {
    throw new OpenwopError(
      'validation_error',
      `The production plan is invalid — fix and regenerate: ${errors.slice(0, 10).join(' ')}`,
      422,
      { errors: errors.slice(0, 10) },
    );
  }
}

export async function savePlan(input: {
  tenantId: string;
  orgId: string;
  planId?: string;
  briefId?: string;
  workflowRunId?: string;
  strategySummary: unknown;
  recommendations?: unknown;
  totalBudget?: unknown;
  timeline?: unknown;
  capabilityAssessment?: unknown;
}): Promise<ProductionPlan> {
  // PIC-2 — closed-world semantic gate at the durable write boundary; fail typed
  // BEFORE any coercion or `plans.put`, so invalid model output never persists.
  assertValidPlanContent(input);
  const planId = optStr(input.planId, MAX.short) ?? `pln:${randomUUID()}`;
  const existing = await getPlan(input.tenantId, input.orgId, planId);
  // PIC-1 — the set of vendorIds that actually exist for this tenant/org, so a
  // recommended vendor that references a non-existent directory row is dropped.
  const knownVendorIds = new Set((await listVendors(input.tenantId, input.orgId)).map((v) => v.vendorId));
  const ts = nowIso();
  const plan: ProductionPlan = {
    planId,
    tenantId: input.tenantId,
    orgId: input.orgId,
    ...(optStr(input.briefId, MAX.short) ? { briefId: optStr(input.briefId, MAX.short) } : {}),
    ...(optStr(input.workflowRunId, MAX.short) ? { workflowRunId: optStr(input.workflowRunId, MAX.short) } : {}),
    strategySummary: cleanStr(input.strategySummary, MAX.notes),
    recommendations: cleanRecommendations(input.recommendations, knownVendorIds),
    totalBudget: cleanBudget(input.totalBudget),
    timeline: cleanTimeline(input.timeline),
    capabilityAssessment: cleanAssessment(input.capabilityAssessment),
    // ADR 0728 D2 — this line used to be defended as "a re-generate never silently
    // un-approves an accepted plan". That is the WEAKER property: preserving the
    // status across a full content replacement does not protect the approval, it
    // DETACHES it — the row would then read "approved by Alice" over content Alice
    // never saw, while `recommendations` is what routes real work to real vendors.
    // The status is still carried (a human's decision is not ours to reset); what
    // changed is that D1 below refuses the replacement outright.
    status: existing?.status ?? 'draft',
    generatedAt: existing?.generatedAt ?? ts,
    updatedAt: ts,
  };
  // ADR 0728 D1 — an approval attests to CONTENT. Once a human has moved a plan out
  // of `draft`, a write that would change what they approved is refused, typed. The
  // comparison is CLEANED-candidate vs stored (this `plan`, built above, not the raw
  // input): `cleanRecommendations` drops unknown vendors, `cleanBudget` normalises
  // the currency and `cleanStr` truncates, so raw-vs-stored would report a difference
  // for input that cleans to the identical record — and the refusal would fire on an
  // honest idempotent retry, which is the one case that MUST keep working.
  if (existing && existing.status !== 'draft' && planContentChanged(existing, plan)) {
    throw new OpenwopError(
      // `conflict` is this codebase's established 409 (163 uses); a feature-local code
      // would mean widening the shared `OpenwopErrorCode` union for one guard. The
      // machine-readable discriminator rides `details.reason`.
      'conflict',
      `Plan '${planId}' is '${existing.status}', not a draft — a human approved its contents. `
      + 'Generating different content into it would leave the approval attached to something nobody reviewed. '
      + 'Generate a new plan instead, or move this one back to draft first.',
      409,
      { reason: 'plan_not_draft', planId, status: existing.status },
    );
  }
  await plans.put(plan);
  return plan;
}

/** ADR 0728 D1 — CONTENT equality for the approval guard. Deliberately excludes the
 *  bookkeeping fields that legitimately differ on every write (`updatedAt`, `updatedBy`,
 *  `generatedAt`, `status`) and the identity fields; comparing those would make every
 *  re-write "changed" and turn the guard into a blanket refusal. */
function planContentChanged(a: ProductionPlan, b: ProductionPlan): boolean {
  return canonicalContent(a) !== canonicalContent(b);
}

/** Stable, semantically-normalised content string for the ADR 0728 D1 comparison.
 *
 *  Canonicalisation is NOT decoration here — it is what makes the guard safe. The
 *  witness caught this: an input naming a vendor that is not in the directory cleans
 *  to `matchingVendors: []`, while the stored record it is otherwise identical to has
 *  NO `matchingVendors` key at all. Both mean "no matching vendors", so a raw
 *  `JSON.stringify` compare would call that a CHANGE and refuse an honest idempotent
 *  retry — the exact failure mode the comparison layer exists to avoid. So: object
 *  keys are sorted (key order is not content), `undefined` is dropped, and an EMPTY
 *  array is treated as absent (the only way a cleaner emits one is "nothing survived",
 *  which is what an absent key already means). */
function canonicalContent(p: ProductionPlan): string {
  const norm = (v: unknown): unknown => {
    if (Array.isArray(v)) {
      const items = v.map(norm).filter((x) => x !== undefined);
      return items.length === 0 ? undefined : items;
    }
    if (v && typeof v === 'object') {
      const out: Record<string, unknown> = {};
      for (const k of Object.keys(v as Record<string, unknown>).sort()) {
        const nv = norm((v as Record<string, unknown>)[k]);
        if (nv !== undefined) out[k] = nv;
      }
      return Object.keys(out).length === 0 ? undefined : out;
    }
    return v === null ? undefined : v;
  };
  return JSON.stringify(norm({
    strategySummary: p.strategySummary,
    recommendations: p.recommendations,
    totalBudget: p.totalBudget,
    timeline: p.timeline,
    capabilityAssessment: p.capabilityAssessment,
    briefId: p.briefId,
  }) ?? {});
}

/** Transition a plan's lifecycle status (advisory-only in v1 — no side-effects). */
export async function transitionPlan(
  tenantId: string,
  orgId: string,
  planId: string,
  status: PlanStatus,
  actor: string,
): Promise<ProductionPlan | null> {
  const p = await getPlan(tenantId, orgId, planId);
  if (!p) return null;
  const next: ProductionPlan = { ...p, status, updatedAt: nowIso(), updatedBy: actor };
  await plans.put(next);
  return next;
}

// ── plan-field sanitizers (untrusted AI output → bounded typed record) ────────
function cleanBudget(raw: unknown): BudgetEstimate {
  const o = (raw ?? {}) as Record<string, unknown>;
  const min = nonNegNum(o.min) ?? 0;
  const max = nonNegNum(o.max) ?? 0;
  // PROD2-R2 — the currency is MODEL-EMITTED and was validated only as a ≤8-char
  // string, so `"dollars"` / `"$"` / `"EUROS"` reached the renderer and threw a
  // `RangeError` out of `Intl.NumberFormat`. Normalised to a real ISO-4217 shape
  // here (the formatter is separately guarded — defence at both ends, because
  // this one keeps GARBAGE OUT OF DURABLE STATE while the guard only keeps the
  // page up). The prompt gives the model bare magnitudes with no unit of
  // account, so inventing a code is the expected behaviour, not an edge case.
  const rawCurrency = cleanStr(o.currency, 8, 'USD');
  const currency = /^[A-Za-z]{3}$/.test(rawCurrency) ? rawCurrency.toUpperCase() : 'USD';
  const budget: BudgetEstimate = { min: Math.min(min, max), max: Math.max(min, max), currency };
  if (Array.isArray(o.breakdown)) {
    budget.breakdown = o.breakdown
      .slice(0, 40)
      .map((b) => {
        const bo = (b ?? {}) as Record<string, unknown>;
        const item = optStr(bo.item, MAX.short);
        const cost = nonNegNum(bo.cost);
        return item && cost !== undefined ? { item, cost } : null;
      })
      .filter((b): b is { item: string; cost: number } => b !== null);
  }
  return budget;
}

function cleanTimeline(raw: unknown): ProductionPlan['timeline'] {
  const o = (raw ?? {}) as Record<string, unknown>;
  const milestones = Array.isArray(o.milestones)
    ? o.milestones
        .slice(0, 40)
        .map((m) => {
          const mo = (m ?? {}) as Record<string, unknown>;
          const date = optStr(mo.date, 40);
          const deliverable = optStr(mo.deliverable, MAX.name);
          return date && deliverable ? { date, deliverable } : null;
        })
        .filter((m): m is { date: string; deliverable: string } => m !== null)
    : [];
  const timeline: ProductionPlan['timeline'] = { milestones };
  const eta = optStr(o.estimatedDeliveryDate, 40);
  if (eta) timeline.estimatedDeliveryDate = eta;
  return timeline;
}

function cleanAssessment(raw: unknown): ProductionPlan['capabilityAssessment'] {
  const o = (raw ?? {}) as Record<string, unknown>;
  const list = (v: unknown): string[] => (Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string').slice(0, 40).map((s) => cleanStr(s, MAX.short)) : []);
  const confRaw = typeof o.confidence === 'number' && Number.isFinite(o.confidence) ? o.confidence : 0.5;
  return {
    strengths: list(o.strengths),
    gaps: list(o.gaps),
    overallRecommendation: cleanStr(o.overallRecommendation, MAX.notes),
    confidence: Math.max(0, Math.min(1, confRaw)),
  };
}

function cleanRecommendations(raw: unknown, knownVendorIds: Set<string>): ProductionRecommendation[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .slice(0, 100)
    .map((r) => {
      const o = (r ?? {}) as Record<string, unknown>;
      const route: ExecutionRoute = (EXECUTION_ROUTES as readonly string[]).includes(String(o.executionRoute))
        ? (o.executionRoute as ExecutionRoute)
        : 'internal';
      const rec: ProductionRecommendation = {
        assetType: cleanStr(o.assetType, MAX.short, 'asset'),
        assetDescription: cleanStr(o.assetDescription, MAX.notes),
        executionRoute: route,
        rationale: cleanStr(o.rationale, MAX.notes),
        budget: cleanBudget(o.budget),
        timelineEstimate: cleanStr(o.timelineEstimate, MAX.short),
      };
      const im = (o.internalMatch ?? null) as Record<string, unknown> | null;
      if (im) {
        rec.internalMatch = {
          suggestedMembers: Array.isArray(im.suggestedMembers)
            ? im.suggestedMembers
                .slice(0, 20)
                .map((m) => {
                  const mo = (m ?? {}) as Record<string, unknown>;
                  return { name: cleanStr(mo.name, MAX.short), role: cleanStr(mo.role, MAX.short), fitReason: cleanStr(mo.fitReason, MAX.short) };
                })
            : [],
          matchingSkills: Array.isArray(im.matchingSkills) ? im.matchingSkills.filter((x): x is string => typeof x === 'string').slice(0, 40) : [],
          gaps: Array.isArray(im.gaps) ? im.gaps.filter((x): x is string => typeof x === 'string').slice(0, 40) : [],
        };
      }
      if (Array.isArray(o.matchingVendors)) {
        rec.matchingVendors = o.matchingVendors
          .slice(0, 20)
          .map((mv) => {
            const mo = (mv ?? {}) as Record<string, unknown>;
            const vendorId = optStr(mo.vendorId, MAX.short);
            const name = optStr(mo.name, MAX.name);
            const type: VendorType = (VENDOR_TYPES as readonly string[]).includes(String(mo.type)) ? (mo.type as VendorType) : 'contractor';
            if (!vendorId || !name) return null;
            // PIC-1 — plan→vendor referential integrity: a matchingVendor must
            // REFERENCE a real directory row for this tenant/org. Drop a
            // fabricated/unknown vendorId (a model can hallucinate one) rather
            // than persist a dangling reference; warn so the hallucination is
            // observable.
            if (!knownVendorIds.has(vendorId)) {
              log.warn('production_plan_vendor_dropped', { vendorId, reason: 'not_in_directory' });
              return null;
            }
            return { vendorId, name, type, matchReason: cleanStr(mo.matchReason, MAX.short) };
          })
          .filter((mv): mv is NonNullable<typeof mv> => mv !== null);
      }
      return rec;
    });
}

/** Test-only reset. */
export async function __resetProduction(): Promise<void> {
  await vendors.__clear();
  await plans.__clear();
}
