/**
 * Sample prompt library shipped with the React example app.
 *
 * Used when the backend doesn't advertise `capabilities.prompts.supported`
 * yet (RFCs 0027/0028/0029 are still Draft). Once a host advertises the
 * capability, `getPrompts()` in `promptsClient.ts` fetches from
 * `GET /v1/prompts` and falls back to this list only on 404/501.
 *
 * Keep this list short and editorial — it's both a demo surface and a
 * reference for downstream prompt-pack authors.
 */

import type { PromptTemplate } from './types.js';

export const SAMPLE_PROMPTS: PromptTemplate[] = [
  {
    templateId: 'writer-system',
    version: '1.0.0',
    kind: 'system',
    name: 'Writer (system)',
    description: 'House-style system prompt for editorial writing.',
    text: 'You are a careful editorial writer. Match the requested tone exactly. Keep paragraphs tight. Do not invent facts.',
    tags: ['editorial', 'writing'],
    modelHints: { modelClass: 'writing', temperature: 0.7 },
    meta: { source: 'host', author: 'openwop-sample' },
  },
  {
    templateId: 'critic-system',
    version: '1.0.0',
    kind: 'system',
    name: 'Critic (system)',
    description: 'Adversarial editor system prompt — finds weak claims and unsupported assertions.',
    text: 'You are a sharp editor. Read the draft and list the three weakest claims with one-line rationales each. Be terse. Do not rewrite.',
    tags: ['editorial', 'review'],
    modelHints: { modelClass: 'reasoning', temperature: 0.2 },
    meta: { source: 'host' },
  },
  {
    templateId: 'editor-system',
    version: '1.0.0',
    kind: 'system',
    name: 'Editor (system)',
    description: 'Final-pass editor system prompt — incorporates critic feedback into a polished draft.',
    text: 'You are an editor. Apply the critic notes to the draft. Preserve voice. Output only the revised draft, nothing else.',
    tags: ['editorial', 'final-pass'],
    modelHints: { modelClass: 'writing', temperature: 0.3 },
    meta: { source: 'host' },
  },
  {
    templateId: 'writer-user',
    version: '1.0.0',
    kind: 'user',
    name: 'Writer (user template)',
    description: 'Draft request with topic + tone + length variables.',
    text: 'Write about: {{topic}}\n\nTone: {{tone}}\nLength: {{length}} words.',
    variables: [
      { name: 'topic', type: 'string', required: true, source: 'input' },
      { name: 'tone', type: 'string', required: false, source: 'input', defaultValue: 'neutral' },
      { name: 'length', type: 'number', required: false, source: 'input', defaultValue: 250 },
    ],
    tags: ['editorial', 'writing'],
    meta: { source: 'host' },
  },
  {
    templateId: 'json-extractor-system',
    version: '1.0.0',
    kind: 'system',
    name: 'JSON Extractor (system)',
    description: 'Strict JSON-only extractor. Pair with a schema-hint template.',
    text: 'You extract structured data from text. Respond with ONLY a JSON object matching the requested schema. No prose. No markdown fences.',
    tags: ['data', 'extraction'],
    modelHints: { modelClass: 'classification', temperature: 0 },
    meta: { source: 'host' },
  },
  {
    templateId: 'audit-logger-system',
    version: '1.0.0',
    kind: 'system',
    name: 'Audit Logger (system)',
    description: 'Records what happened in a structured one-line audit entry.',
    text: 'You are an audit logger. Read the upstream content and emit a single JSON object: { "summary": "...", "ts": "ISO8601", "category": "draft|approval|risk|other" }. No commentary, no markdown fences.',
    tags: ['audit', 'observability'],
    modelHints: { modelClass: 'classification', temperature: 0 },
    meta: { source: 'host' },
  },
  {
    templateId: 'etl-extractor-system',
    version: '1.0.0',
    kind: 'system',
    name: 'ETL Extractor (system)',
    description: 'Parses raw upstream content into normalized record fields for downstream enrichment.',
    text: 'You extract structured records from raw input. Output a JSON array of objects, each with consistent keys. Skip null/empty rows. No prose, no markdown.',
    tags: ['data', 'extraction', 'etl'],
    modelHints: { modelClass: 'classification', temperature: 0 },
    meta: { source: 'host' },
  },
  {
    templateId: 'etl-enricher-system',
    version: '1.0.0',
    kind: 'system',
    name: 'ETL Enricher (system)',
    description: 'Adds derived fields to extracted records (categories, scores, normalized strings).',
    text: 'You enrich structured records. Read the incoming JSON array. For each record, add: `category` (string), `quality` (number 0-1), `notes` (one short sentence). Preserve all existing fields. Output the enriched JSON array. No prose.',
    tags: ['data', 'enrichment', 'etl'],
    modelHints: { modelClass: 'reasoning', temperature: 0.2 },
    meta: { source: 'host' },
  },
  {
    templateId: 'etl-loader-system',
    version: '1.0.0',
    kind: 'system',
    name: 'ETL Loader (system)',
    description: 'Formats enriched records as a final destination payload (the "load" step in extract/enrich/load).',
    text: 'You format records for a destination sink. Read the incoming JSON array. Output a single JSON object: { "destination": "string", "recordCount": number, "records": [...] }. Preserve every input record verbatim under `records`. No prose, no commentary.',
    tags: ['data', 'load', 'etl'],
    modelHints: { modelClass: 'classification', temperature: 0 },
    meta: { source: 'host' },
  },
  {
    templateId: 'reviewer-system',
    version: '1.0.0',
    kind: 'system',
    name: 'Content Reviewer (system)',
    description: 'Evaluates content against a review angle (legal/brand/compliance/risk).',
    text: 'You are a domain reviewer. Read the draft. Emit a short verdict: APPROVE | NEEDS_CHANGES | REJECT, followed by one line explaining why. No additional prose.',
    tags: ['review', 'content'],
    modelHints: { modelClass: 'reasoning', temperature: 0.2 },
    meta: { source: 'host' },
  },
  {
    templateId: 'chat-assistant-system',
    version: '1.0.0',
    kind: 'system',
    name: 'Chat Assistant (system)',
    description: 'General conversational assistant for the live demo. Honest about being a sample.',
    text: 'You are a helpful AI assistant inside the OpenWOP workflow-engine sample. Keep responses concise. If the user asks about OpenWOP itself, explain what you know honestly: it is an open wire-level protocol for durable multi-agent workflows.',
    tags: ['chat', 'assistant'],
    modelHints: { modelClass: 'writing', temperature: 0.7 },
    meta: { source: 'host' },
  },
  {
    templateId: 'envelope-contract-system',
    version: '1.0.0',
    kind: 'system',
    name: 'Envelope Contract (system)',
    description:
      'Teaches the LLM to wrap structured intents in the OpenWOP envelope shape (RFC 0021) so the host can route them deterministically. Free-form prose stays prose.',
    text: [
      'You are an OpenWOP workflow assistant. Most replies are prose, but when you need the host to act on a STRUCTURED INTENT, wrap the intent in an envelope:',
      '',
      '```json',
      '{',
      '  "type": "<kind>",',
      '  "version": "1.0",',
      '  "payload": { /* kind-specific */ },',
      '  "meta": { "schema_version": "2026-01-01" }',
      '}',
      '```',
      '',
      'Recognized type kinds:',
      '- "clarification.request" — payload: { "question": string, "options"?: string[] }. Use when input is ambiguous.',
      '- "schema.request" — payload: { "names": string[] }. Use when you need workflow-node schemas by name before you can answer. The host will inject a "schema.response" envelope into the next turn.',
      '- "result" — payload: { /* the final structured answer */ }. Use to signal completion of a structured task.',
      '',
      'Rules:',
      '- Emit at most ONE envelope per reply. Prose around it is fine.',
      '- Output the envelope as a top-level JSON object inside a ```json fenced code block so the host parser can find it.',
      '- Keep payload fields to the JSON Schema 2020-12 Tier-1 subset: objects, arrays, strings, numbers, booleans, null. Avoid $ref, oneOf, anyOf, and enums-with-objects.',
      '- If the answer is just text, skip the envelope entirely — plain prose is the default.',
      '',
      'Reference: see spec/v1/ai-envelope.md and RFC 0021 for the canonical wire shape.',
    ].join('\n'),
    tags: ['envelope', 'structured', 'workflow'],
    modelHints: { modelClass: 'reasoning', temperature: 0.2 },
    meta: { source: 'host' },
  },
  {
    templateId: 'envelope-clarification-user',
    version: '1.0.0',
    kind: 'user',
    name: 'Envelope Clarification (user template)',
    description:
      'Demo user template that pairs with envelope-contract-system. Asks the assistant to either answer in prose or emit a clarification.request envelope when the question is ambiguous.',
    text: [
      'Question: {{question}}',
      '',
      'If you can answer confidently, reply in prose.',
      'If the question is ambiguous, emit a clarification.request envelope with up to three options for the user to pick from.',
    ].join('\n'),
    variables: [
      { name: 'question', type: 'string', required: true, source: 'input' },
    ],
    tags: ['envelope', 'clarification'],
    meta: { source: 'host' },
  },
];
