/**
 * Content digest for a pack directory — the ONE hashing rule shared by both
 * attestation sources in the ADR 0555 trust model.
 *
 *   - `operator-trusted` — `.openwop-installed.json`'s `contentHashes`, written
 *     at install time after SRI + Ed25519 verification, re-checked on load.
 *   - `steward` — `packs/.steward-manifest.json`, a committed digest per pack
 *     generated by `scripts/gen-steward-manifest.mjs`.
 *
 * ── ONE ALGORITHM, TWO IMPLEMENTATIONS, AND WHY ───────────────────────────
 *
 * The generator is a plain `.mjs` script that must run in `scripts/ci.sh`
 * BEFORE the backend build, so it cannot import this compiled module, and the
 * backend bundle must not reach up into `scripts/`. So the digest is written
 * twice: here, and in `scripts/lib/pack-content-digest.mjs`.
 *
 * That duplication is the drift hazard the ADR 0555 review flagged, and drift
 * here is CATASTROPHIC rather than cosmetic: if the two disagree, every pack
 * fails steward attestation at once and — because the policy is fail-closed —
 * the whole product stops dispatching. So the duplication is pinned by
 * `pack-content-digest-parity.test.ts`, which runs BOTH implementations over
 * the same fixtures and asserts byte-equal output. Change one, that test goes
 * red. (Same shape as the repo's `promptCatalogParity` tests: two copies are
 * acceptable only when a test makes divergence impossible to merge.)
 *
 * ── WHAT IS HASHED ────────────────────────────────────────────────────────
 *
 * Every entry under the pack dir, recursively, sorted by POSIX-normalised
 * relative path, folded into one sha256 over `\<relpath\>\0\<kind\>\0\<leaf\>\n`
 * lines. Three kinds, so a swap between them changes the digest:
 *
 *   f  regular file  → leaf is sha256 of the bytes
 *   l  symlink       → leaf is sha256 of the LINK TARGET STRING, never the
 *                      target's content. A pack that swaps a file for a symlink
 *                      pointing at `/etc/passwd` (or at another pack's code)
 *                      must not be able to keep its digest.
 *   o  other         → leaf is the empty-string sha256; presence alone is
 *                      recorded (fifo/socket/device — never legitimate in a
 *                      pack, but silently ignoring them would let one hide).
 *
 * Directories contribute only through their children's paths; an empty
 * directory is invisible, which is correct — it carries no code.
 *
 * NOTE this is strictly STRONGER than the install marker it sits beside.
 * `registryInstaller` writes `contentHashes` for `pack.json` + `index.mjs`
 * ONLY, so an auxiliary `./lib/helper.mjs` that `index.mjs` imports is not
 * covered by `verifyInstalledPack()`. That gap is pre-existing and out of
 * ADR 0555 P0's scope (recorded in the ADR as residue), but it is the reason
 * `steward` and `operator-trusted` are NOT interchangeable evidence: steward
 * attests every byte, operator-trusted attests two files plus a signature.
 */

import { createHash } from 'node:crypto';
import { lstatSync, readdirSync, readFileSync, readlinkSync } from 'node:fs';
import { join } from 'node:path';

/** Never part of a pack's content digest. */
const EXCLUDED_NAMES = new Set([
  // Written by the installer AFTER the bytes are in place, and it contains the
  // hashes themselves — including it would be self-referential.
  '.openwop-installed.json',
  'node_modules',
  '.git',
  '.DS_Store',
]);

const EMPTY_SHA256 = createHash('sha256').update('').digest('hex');

export interface PackDigestEntry {
  /** POSIX-normalised path relative to the pack dir. */
  path: string;
  kind: 'f' | 'l' | 'o';
  /** sha256 of the file bytes / of the link target string / of '' for other. */
  leaf: string;
}

/**
 * Enumerate a pack's content entries, sorted by path.
 *
 * `lstat`, never `stat`: following a symlink here would hash the TARGET's
 * content, so a pack could point `index.mjs` at a file outside itself and
 * inherit that file's digest. We record the link string instead.
 */
export function listPackEntries(packDir: string): PackDigestEntry[] {
  const out: PackDigestEntry[] = [];

  const walk = (absDir: string, relPrefix: string): void => {
    let names: string[];
    try {
      names = readdirSync(absDir);
    } catch {
      // An unreadable directory contributes nothing. The caller's digest then
      // won't match the manifest, which fails CLOSED — the correct outcome.
      return;
    }
    for (const name of names.sort()) {
      if (EXCLUDED_NAMES.has(name)) continue;
      const abs = join(absDir, name);
      const rel = relPrefix ? `${relPrefix}/${name}` : name;
      let st;
      try {
        st = lstatSync(abs);
      } catch {
        continue;
      }
      if (st.isSymbolicLink()) {
        let target = '';
        try {
          target = readlinkSync(abs);
        } catch {
          target = '';
        }
        out.push({ path: rel, kind: 'l', leaf: createHash('sha256').update(target).digest('hex') });
      } else if (st.isDirectory()) {
        walk(abs, rel);
      } else if (st.isFile()) {
        let leaf: string;
        try {
          leaf = createHash('sha256').update(readFileSync(abs)).digest('hex');
        } catch {
          continue;
        }
        out.push({ path: rel, kind: 'f', leaf });
      } else {
        out.push({ path: rel, kind: 'o', leaf: EMPTY_SHA256 });
      }
    }
  };

  walk(packDir, '');
  out.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return out;
}

/**
 * Fold a pack directory into one hex sha256.
 *
 * The top-level `packDir` may itself be a symlink (every dev-mounted pack in
 * `~/.openwop-packs` is one) — `readdirSync` follows it, which is intended:
 * we are digesting the CONTENT the loader will import, wherever it lives.
 * Symlink handling above applies to entries INSIDE the pack.
 */
export function packContentDigest(packDir: string): string {
  const h = createHash('sha256');
  for (const e of listPackEntries(packDir)) {
    h.update(`${e.path}\0${e.kind}\0${e.leaf}\n`);
  }
  return h.digest('hex');
}

/**
 * Re-verify an install marker's per-file `contentHashes` map.
 *
 * Extracted from `registryInstaller.verifyInstalledPack()` so the marker path
 * and the steward path share one hasher rather than two that can disagree.
 * Returns `null` when every listed file matches, else a reason string naming
 * the first offending path.
 */
export function verifyContentHashes(
  packDir: string,
  contentHashes: Record<string, string>,
): string | null {
  for (const [relPath, expectedSha] of Object.entries(contentHashes)) {
    const filePath = join(packDir, relPath);
    let actual: string;
    try {
      actual = createHash('sha256').update(readFileSync(filePath)).digest('hex');
    } catch {
      return `content_missing:${relPath}`;
    }
    if (actual !== expectedSha) return `content_modified:${relPath}`;
  }
  return null;
}
